import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildOfficialPairRoleStats } from "./pair_role_stats.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const argv = process.argv.slice(2);
const opt = (name, fallback) => {
  const index = argv.indexOf(name);
  return index >= 0 ? argv[index + 1] : fallback;
};

const input = path.resolve(ROOT, opt("--in", "src/officialMatchStats.compact.json"));
const output = path.resolve(ROOT, opt("--out", "src/pairRoleStats.js"));
const minGames = Number(opt("--min-games", 60));
const minCandidates = Number(opt("--min-candidates", 2));

if (!fs.existsSync(input)) throw new Error(`Input not found: ${path.relative(ROOT, input)}`);

const source = JSON.parse(await fsp.readFile(input, "utf8"));
const officialPairRoleStatsByTier = buildOfficialPairRoleStats(
  source.officialCompositionStatsByTier,
  { minGames, minCandidates },
);
const pairRoleStatsMeta = {
  generatedAt: source.source?.generatedAt ?? new Date().toISOString(),
  sourceGeneratedAt: source.source?.generatedAt ?? null,
  sourceTeams: source.source?.validTeams ?? null,
  minGames,
  minCandidates,
  rowsByTier: Object.fromEntries(
    Object.entries(officialPairRoleStatsByTier).map(([bucket, rows]) => [bucket, Object.keys(rows).length]),
  ),
};

const content = `// Generated by tools/build_pair_role_stats.mjs. Do not edit by hand.\n` +
  `export const pairRoleStatsMeta = ${JSON.stringify(pairRoleStatsMeta, null, 2)};\n\n` +
  `export const officialPairRoleStatsByTier = ${JSON.stringify(officialPairRoleStatsByTier, null, 2)};\n`;

await fsp.mkdir(path.dirname(output), { recursive: true });
await fsp.writeFile(output, content, "utf8");
console.log(`Pair-role stats written: ${path.relative(ROOT, output)}`);
console.log(`Rows by tier: ${JSON.stringify(pairRoleStatsMeta.rowsByTier)}`);
