/**
 * build_tournament_meta.mjs — regenerate src/tournamentMeta.js from collected
 * tournament games.
 *
 * src/tournamentMeta.js says "AUTO-GENERATED by tools/tournament_collector.mjs",
 * but that collector only writes the raw JSON - nothing turned it into the module.
 * So the file was frozen at its 2026-06-10 build, which is season 39, while the
 * recommender still scores against it.
 *
 * Pro games are worth keeping separate from ranked because the composition signal
 * is far more concentrated: in the season-39 set one trio accounted for 27 of 79
 * games. Ranked averages that away over millions of matches.
 *
 * Usage:
 *   node tools/build_tournament_meta.mjs --in data/tournament_s41.json
 *   node tools/build_tournament_meta.mjs --in a.json --in b.json --min-appearances 2
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src", "tournamentMeta.js");

function parseArgs() {
  // "current" resolves to the highest seasonId in the input. Pro compositions are a
  // per-patch quantity and mixing seasons would average away the very thing that
  // makes this data worth keeping separate from ranked; a hard-coded number would
  // just rot the next time a season rolls over.
  const args = { in: [], minAppearances: 2, out: OUT, minSeason: "current" };
  for (let i = 2; i < process.argv.length; i += 1) {
    const key = process.argv[i];
    if (!key.startsWith("--")) continue;
    const value = process.argv[i + 1];
    i += 1;
    if (key === "--in") args.in.push(path.resolve(ROOT, value));
    if (key === "--out") args.out = path.resolve(ROOT, value);
    if (key === "--min-appearances") args.minAppearances = Number(value);
    if (key === "--min-season") args.minSeason = value === "any" ? null : value;
  }
  if (!args.in.length) args.in = [path.join(ROOT, "data", "tournament_s41.json")];
  return args;
}

async function main() {
  const args = parseArgs();
  const { characters } = await import(`file://${path.join(ROOT, "src", "data.js").replace(/\\/g, "/")}`);

  // The collector stores official character codes; the app keys everything by local
  // id, so the same code map the stats pipeline uses has to be applied here too.
  const { FALLBACK_CHARACTER_CODE_TO_ID } = await import(
    `file://${path.join(ROOT, "tools", "character_code_map.mjs").replace(/\\/g, "/")}`
  );
  const known = new Set(characters.map((c) => c.id));
  const idOf = (code) => {
    const id = FALLBACK_CHARACTER_CODE_TO_ID[String(code)];
    return id && known.has(id) ? id : null;
  };

  const records = [];
  for (const file of args.in) {
    const rows = JSON.parse(await fs.readFile(file, "utf8"));
    records.push(...rows);
    console.log(`read ${path.relative(ROOT, file)}: ${rows.length} team rows`);
  }

  // Rows collected before 2026-09-05 carry no seasonId; treat those as unknown and
  // keep them only when no filter is asked for.
  let resolvedSeason = null;
  if (args.minSeason !== null) {
    const seasons = records.map((r) => r.seasonId).filter((id) => Number.isFinite(id) && id > 0);
    resolvedSeason = args.minSeason === "current"
      ? (seasons.length ? seasons.reduce((a, b) => (b > a ? b : a), 0) : null)
      : Number(args.minSeason);
  }
  if (resolvedSeason !== null) {
    const before = records.length;
    const kept = records.filter((r) => Number.isFinite(r.seasonId) && r.seasonId >= resolvedSeason);
    console.log(`season filter: >= ${resolvedSeason} keeps ${kept.length} of ${before} team rows`);
    records.length = 0;
    for (const row of kept) records.push(row);
  }
  if (!records.length) {
    console.error("No team rows left after filtering - refusing to write an empty module.");
    process.exit(1);
  }

  const gameIds = new Set(records.map((r) => r.gameId));
  const charStats = {};
  const compMap = new Map();
  let dropped = 0;

  for (const r of records) {
    const ids = (r.characterNums ?? []).map(idOf);
    if (ids.length !== 3 || ids.some((x) => !x)) { dropped += 1; continue; }
    for (const id of ids) {
      const stat = (charStats[id] ??= { picks: 0, wins: 0, top3: 0 });
      stat.picks += 1;
      stat.wins += r.win ? 1 : 0;
      stat.top3 += r.top3 ? 1 : 0;
    }
    const key = [...ids].sort().join("|");
    const comp = compMap.get(key) ?? { members: [...ids].sort(), appearances: 0, place: 0, ts: 0, ks: 0 };
    comp.appearances += 1;
    comp.place += r.placement ?? 0;
    comp.ts += r.rankScore ?? 0;
    comp.ks += r.killScore ?? 0;
    compMap.set(key, comp);
  }

  const round = (v, d = 2) => Math.round(v * 10 ** d) / 10 ** d;
  const compositions = [...compMap.values()]
    .filter((c) => c.appearances >= args.minAppearances)
    .map((c) => ({
      members: c.members,
      appearances: c.appearances,
      rank: round(c.place / c.appearances),
      ts: round(c.ts / c.appearances),
      ks: round(c.ks / c.appearances),
    }))
    .sort((a, b) => b.appearances - a.appearances || a.rank - b.rank);

  console.log(`games ${gameIds.size} | team rows ${records.length} | unmapped dropped ${dropped}`);
  console.log(`characters ${Object.keys(charStats).length} | compositions (>=${args.minAppearances}) ${compositions.length}`);

  const missing = characters.filter((c) => !charStats[c.id]).map((c) => c.id);
  if (missing.length) {
    console.log(`never picked: ${missing.slice(0, 10).join(", ")}${missing.length > 10 ? ` (+${missing.length - 10})` : ""}`);
  }

  const body = [
    "// AUTO-GENERATED by tools/build_tournament_meta.mjs. Do not edit by hand.",
    `// Source: ${gameIds.size} tournament games from ${args.in.map((f) => path.basename(f)).join(", ")}`,
    `// Season filter: ${resolvedSeason === null ? "none" : `>= ${resolvedSeason}`}`,
    `// Generated: ${new Date().toISOString()}`,
    `// ${compositions.length} compositions with ${args.minAppearances}+ appearances`,
    "",
    `export const tournamentTotalGames = ${gameIds.size};`,
    "",
    "// Per-character pick/win/top3 counts (string IDs matching characterVariants)",
    `export const tournamentCharStats = ${JSON.stringify(charStats, null, 2)};`,
    "",
    "export const tournamentCompositions = [",
    ...compositions.map((c) => `  ${JSON.stringify(c)},`),
    "];",
    "",
  ].join("\n");

  await fs.writeFile(args.out, body, "utf8");
  console.log(`wrote ${path.relative(ROOT, args.out)}`);
}

main().catch((error) => { console.error(error); process.exit(1); });
