/**
 * character_code_map.mjs — official character code -> local id.
 *
 * This map lived in three separate tools. When Craver was added only two of them
 * were updated, so the empirical spectrum report silently dropped him; the same
 * gap would have swallowed Lucia. One copy, imported everywhere.
 *
 * It is a fallback: build_official_stats overlays the live API character list on
 * top where that is available. The API data endpoint is frozen well behind the
 * live roster, so the tail of this map is what actually resolves new characters.
 */
export const FALLBACK_CHARACTER_CODE_TO_ID = {
  1: "jackie",
  2: "aya",
  3: "fiora",
  4: "magnus",
  5: "zahir",
  6: "nadine",
  7: "hyunwoo",
  8: "hart",
  9: "isol",
  10: "li_dailin",
  11: "yuki",
  12: "hyejin",
  13: "sho",
  14: "chiara",
  15: "sissela",
  16: "silvia",
  17: "adriana",
  18: "shoichi",
  19: "emma",
  20: "lenox",
  21: "rozzi",
  22: "luke",
  23: "cathy",
  24: "adela",
  25: "bernice",
  26: "barbara",
  27: "alex",
  28: "sua",
  29: "leon",
  30: "eleven",
  31: "rio",
  32: "william",
  33: "nicky",
  34: "nathapon",
  35: "yan",
  36: "eva",
  37: "daniel",
  38: "jenny",
  39: "camilo",
  40: "chloe",
  41: "johann",
  42: "bianca",
  43: "celine",
  44: "echion",
  45: "mai",
  46: "aiden",
  47: "laura",
  48: "tia",
  49: "felix",
  50: "elena",
  51: "priya",
  52: "adina",
  53: "markus",
  54: "karla",
  55: "estelle",
  56: "piolo",
  57: "martina",
  58: "haze",
  59: "isaac",
  60: "tazia",
  61: "irem",
  62: "theodore",
  63: "ian",
  64: "vanya",
  65: "debi_marlene",
  66: "arda",
  67: "abigail",
  68: "alonso",
  69: "leni",
  70: "tsubame",
  71: "kenneth",
  72: "katja",
  73: "charlotte",
  74: "darko",
  75: "lenore",
  76: "garnet",
  77: "yumin",
  78: "hisui",
  79: "justina",
  80: "istvan",
  81: "nia",
  82: "shirin",
  83: "henry",
  84: "blair",
  85: "mirka",
  86: "fenrir",
  87: "coreline",
  88: "bihyung",
  89: "craver",
  90: "lucia",
};

export const characterIdForCode = (code) => FALLBACK_CHARACTER_CODE_TO_ID[String(code)] ?? null;
