import { skinTemplates } from "./skinTemplates.js";

export const roles = [
  { id: "frontline", label: "탱커" },
  { id: "bruiser", label: "브루저" },
  { id: "ranged", label: "원거리 딜러" },
  { id: "assassin", label: "암살자" },
  { id: "mage", label: "스킬 딜러" },
  { id: "support", label: "서포터" },
];

export const weaponTypes = {
  dagger: { label: "단검", range: "melee" },
  two_handed_sword: { label: "양손검", range: "melee" },
  axe: { label: "도끼", range: "melee" },
  dual_swords: { label: "쌍검", range: "melee" },
  pistol: { label: "권총", range: "ranged" },
  assault_rifle: { label: "돌격소총", range: "ranged" },
  sniper_rifle: { label: "저격총", range: "ranged" },
  rapier: { label: "레이피어", range: "melee" },
  spear: { label: "창", range: "melee" },
  hammer: { label: "망치", range: "melee" },
  bat: { label: "방망이", range: "melee" },
  throw: { label: "투척", range: "ranged" },
  shuriken: { label: "암기", range: "ranged" },
  bow: { label: "활", range: "ranged" },
  crossbow: { label: "석궁", range: "ranged" },
  glove: { label: "글러브", range: "melee" },
  tonfa: { label: "톤파", range: "melee" },
  guitar: { label: "기타", range: "ranged" },
  nunchaku: { label: "쌍절곤", range: "melee" },
  whip: { label: "채찍", range: "melee" },
  camera: { label: "카메라", range: "ranged" },
  arcana: { label: "아르카나", range: "ranged" },
  vf_prosthetic: { label: "VF 의수", range: "melee" },
  flex: { label: "통합", range: "hybrid" },
  unknown: { label: "무기 확인 필요", range: "unknown" },
};

function c(id, name, role, tags, damage = "skill", difficulty = 3) {
  return { id, name, role, tags, damage, difficulty };
}

export const characters = [
  c("garnet", "가넷", "frontline", ["durable", "initiate", "cc"], "hybrid", 3),
  c("nadine", "나딘", "ranged", ["sustained", "range", "objective"], "basic", 4),
  c("nathapon", "나타폰", "mage", ["poke", "zone", "cc"], "skill", 4),
  c("nia", "니아", "ranged", ["poke", "burst", "focus"], "skill", 3),
  c("nicky", "니키", "frontline", ["initiate", "cc", "durable"], "hybrid", 3),
  c("daniel", "다니엘", "assassin", ["burst", "dive", "focus"], "skill", 4),
  c("darko", "다르코", "frontline", ["initiate", "cc", "durable"], "hybrid", 3),
  c("debi_marlene", "데비&마를렌", "bruiser", ["dive", "sustained", "mobility"], "basic", 4),
  c("tia", "띠아", "mage", ["poke", "zone", "cc"], "skill", 4),
  c("laura", "라우라", "bruiser", ["dive", "burst", "focus"], "skill", 4),
  c("lenox", "레녹스", "frontline", ["initiate", "peel", "cc", "durable"], "skill", 2),
  c("leni", "레니", "support", ["peel", "healing", "utility"], "skill", 3),
  c("leon", "레온", "bruiser", ["dive", "cc", "durable"], "hybrid", 2),
  c("rozzi", "로지", "ranged", ["sustained", "mobility", "burst"], "basic", 4),
  c("luke", "루크", "bruiser", ["dive", "sustained", "duel"], "basic", 2),
  c("lenore", "르노어", "mage", ["poke", "zone", "utility"], "skill", 4),
  c("li_dailin", "리 다이린", "bruiser", ["dive", "cc", "duel"], "hybrid", 3),
  c("rio", "리오", "ranged", ["sustained", "range", "objective"], "basic", 4),
  c("martina", "마르티나", "ranged", ["range", "objective", "utility"], "basic", 4),
  c("mai", "마이", "frontline", ["peel", "shield", "durable"], "skill", 3),
  c("markus", "마커스", "frontline", ["initiate", "cc", "durable"], "hybrid", 3),
  c("magnus", "매그너스", "frontline", ["initiate", "cc", "durable"], "hybrid", 2),
  c("mirka", "미르카", "bruiser", ["dive", "burst", "mobility"], "hybrid", 3),
  c("vanya", "바냐", "mage", ["poke", "shield", "zone"], "skill", 3),
  c("barbara", "바바라", "mage", ["zone", "poke", "objective"], "skill", 4),
  c("bernice", "버니스", "ranged", ["range", "cc", "sustained"], "basic", 3),
  c("blair", "블레어", "mage", ["poke", "zone", "burst"], "skill", 3),
  c("bianca", "비앙카", "mage", ["burst", "zone", "sustain"], "skill", 4),
  c("bihyung", "비형", "assassin", ["burst", "dive", "mobility"], "skill", 4),
  c("charlotte", "샬럿", "support", ["healing", "shield", "peel"], "skill", 2),
  c("celine", "셀린", "mage", ["burst", "zone", "poke"], "skill", 5),
  c("sho", "쇼우", "frontline", ["durable", "peel", "sustained"], "hybrid", 3),
  c("shoichi", "쇼이치", "assassin", ["burst", "dive", "mobility"], "skill", 5),
  c("sua", "수아", "bruiser", ["cc", "durable", "sustained"], "skill", 3),
  c("shirin", "슈린", "bruiser", ["sustain", "peel", "utility"], "skill", 3),
  c("sissela", "시셀라", "mage", ["poke", "burst", "zone", "cc"], "skill", 4),
  c("silvia", "실비아", "bruiser", ["mobility", "poke", "dive"], "hybrid", 5),
  c("adela", "아델라", "mage", ["zone", "burst", "cc"], "skill", 5),
  c("adriana", "아드리아나", "mage", ["zone", "poke", "objective"], "skill", 4),
  c("adina", "아디나", "mage", ["poke", "utility", "zone"], "skill", 5),
  c("arda", "아르다", "mage", ["poke", "cc", "zone"], "skill", 3),
  c("abigail", "아비게일", "bruiser", ["dive", "burst", "durable"], "skill", 3),
  c("aya", "아야", "ranged", ["sustained", "range", "objective"], "basic", 1),
  c("isol", "아이솔", "ranged", ["poke", "zone", "objective"], "basic", 3),
  c("isaac", "아이작", "bruiser", ["dive", "sustained", "pick"], "hybrid", 3),
  c("alex", "알렉스", "bruiser", ["dive", "burst", "focus"], "hybrid", 5),
  c("alonso", "알론소", "frontline", ["initiate", "cc", "durable"], "skill", 3),
  c("yan", "얀", "bruiser", ["dive", "cc", "durable"], "hybrid", 3),
  c("estelle", "에스텔", "frontline", ["peel", "shield", "cc", "durable"], "skill", 3),
  c("aiden", "에이든", "bruiser", ["dive", "burst", "mobility"], "hybrid", 4),
  c("echion", "에키온", "bruiser", ["dive", "sustained", "durable"], "skill", 4),
  c("elena", "엘레나", "frontline", ["initiate", "cc", "durable"], "skill", 3),
  c("emma", "엠마", "mage", ["poke", "cc", "utility"], "skill", 4),
  c("johann", "요한", "support", ["healing", "shield", "peel"], "skill", 2),
  c("william", "윌리엄", "ranged", ["sustained", "poke", "objective"], "basic", 4),
  c("yumin", "유민", "ranged", ["utility", "poke", "focus"], "skill", 3),
  c("justina", "유스티나", "ranged", ["range", "burst", "mobility"], "basic", 3),
  c("yuki", "유키", "bruiser", ["engage", "cc", "burst", "duel"], "hybrid", 2),
  c("irem", "이렘", "mage", ["poke", "mobility", "utility"], "skill", 4),
  c("eva", "이바", "mage", ["poke", "range", "zone"], "skill", 3),
  c("istvan", "이슈트반", "bruiser", ["dive", "durable", "sustained"], "hybrid", 3),
  c("ian", "이안", "bruiser", ["burst", "dive", "focus"], "skill", 4),
  c("eleven", "일레븐", "frontline", ["initiate", "cc", "durable"], "skill", 2),
  c("zahir", "자히르", "mage", ["poke", "cc", "range"], "skill", 4),
  c("jackie", "재키", "bruiser", ["dive", "sustained", "mobility"], "basic", 2),
  c("jenny", "제니", "mage", ["poke", "burst", "mobility"], "skill", 3),
  c("tsubame", "츠바메", "assassin", ["burst", "dive", "mobility"], "skill", 5),
  c("camilo", "카밀로", "bruiser", ["dive", "sustained", "mobility"], "basic", 4),
  c("katja", "카티야", "ranged", ["range", "burst", "pick"], "basic", 3),
  c("karla", "칼라", "ranged", ["poke", "range", "cc"], "basic", 4),
  c("cathy", "캐시", "assassin", ["burst", "dive", "mobility", "pick"], "skill", 3),
  c("kenneth", "케네스", "bruiser", ["dive", "durable", "sustained"], "hybrid", 3),
  c("coreline", "코렐라인", "mage", ["poke", "zone", "utility"], "skill", 4),
  c("chloe", "클로에", "ranged", ["poke", "sustained", "utility"], "skill", 4),
  c("chiara", "키아라", "bruiser", ["dive", "durable", "sustained"], "skill", 3),
  c("tazia", "타지아", "mage", ["poke", "zone", "burst"], "skill", 4),
  c("theodore", "테오도르", "ranged", ["poke", "shield", "range", "utility"], "skill", 3),
  c("fenrir", "펜리르", "bruiser", ["dive", "sustained", "durable"], "hybrid", 3),
  c("felix", "펠릭스", "bruiser", ["dive", "sustained", "mobility"], "basic", 4),
  c("priya", "프리야", "support", ["healing", "cc", "utility"], "skill", 3),
  c("fiora", "피오라", "bruiser", ["dive", "duel", "sustained"], "basic", 3),
  c("piolo", "피올로", "bruiser", ["dive", "cc", "mobility"], "hybrid", 4),
  c("hart", "하트", "ranged", ["sustained", "poke", "mobility"], "basic", 3),
  c("haze", "헤이즈", "mage", ["poke", "burst", "range"], "skill", 3),
  c("henry", "헨리", "ranged", ["range", "poke", "objective"], "basic", 3),
  c("hyunwoo", "현우", "bruiser", ["initiate", "cc", "durable", "focus"], "hybrid", 2),
  c("hyejin", "혜진", "mage", ["poke", "cc", "burst"], "skill", 4),
  c("hisui", "히스이", "bruiser", ["burst", "dive", "focus"], "skill", 4),
];

export const characterWeapons = {
  abigail: ["axe"],
  adela: ["rapier", "bat"],
  adriana: ["throw"],
  adina: ["arcana"],
  aiden: ["two_handed_sword"],
  alex: ["flex"],
  alonso: ["glove"],
  arda: ["arcana"],
  aya: ["pistol", "assault_rifle", "sniper_rifle"],
  barbara: ["pistol"],
  bernice: ["sniper_rifle"],
  bianca: ["arcana"],
  bihyung: ["bat"],
  blair: ["dual_swords"],
  camilo: ["dual_swords", "rapier"],
  cathy: ["dagger", "dual_swords"],
  celine: ["throw"],
  charlotte: ["arcana"],
  chiara: ["rapier"],
  chloe: ["shuriken"],
  coreline: ["arcana"],
  daniel: ["dagger"],
  darko: ["bat"],
  debi_marlene: ["two_handed_sword"],
  echion: ["vf_prosthetic"],
  eleven: ["hammer"],
  elena: ["rapier"],
  emma: ["shuriken", "arcana"],
  estelle: ["axe"],
  eva: ["throw"],
  felix: ["spear"],
  fenrir: ["glove"],
  fiora: ["two_handed_sword", "rapier", "spear"],
  garnet: ["bat"],
  hart: ["guitar"],
  haze: ["assault_rifle"],
  henry: ["shuriken"],
  hisui: ["two_handed_sword"],
  hyejin: ["shuriken", "bow"],
  hyunwoo: ["glove", "tonfa"],
  ian: ["dagger"],
  irem: ["throw"],
  isaac: ["tonfa"],
  isol: ["pistol", "assault_rifle"],
  istvan: ["spear"],
  jackie: ["dagger", "two_handed_sword", "axe", "dual_swords"],
  jenny: ["pistol"],
  johann: ["arcana"],
  justina: ["crossbow"],
  karla: ["crossbow"],
  katja: ["sniper_rifle"],
  kenneth: ["axe"],
  laura: ["whip"],
  leni: ["pistol"],
  lenore: ["guitar"],
  lenox: ["whip"],
  leon: ["glove", "tonfa"],
  li_dailin: ["glove", "nunchaku"],
  luke: ["bat"],
  magnus: ["hammer", "bat"],
  mai: ["whip"],
  markus: ["axe", "hammer"],
  martina: ["camera"],
  mirka: ["hammer"],
  nadine: ["bow", "crossbow"],
  nathapon: ["camera"],
  nia: ["pistol"],
  nicky: ["glove"],
  piolo: ["nunchaku"],
  priya: ["guitar"],
  rio: ["bow"],
  rozzi: ["pistol"],
  shirin: ["rapier"],
  sho: ["dagger", "spear"],
  shoichi: ["dagger"],
  silvia: ["pistol"],
  sissela: ["throw", "shuriken"],
  sua: ["hammer", "bat"],
  tazia: ["shuriken"],
  theodore: ["sniper_rifle"],
  tia: ["bat"],
  tsubame: ["shuriken"],
  vanya: ["arcana"],
  william: ["throw"],
  yan: ["glove", "tonfa"],
  yuki: ["two_handed_sword", "dual_swords"],
  yumin: ["arcana"],
  zahir: ["throw", "shuriken"],
};

export const variantOverrides = {
  "jackie:dagger": { role: "assassin", tags: ["burst", "dive", "focus"] },
  "magnus:bat": { role: "bruiser", tags: ["dive", "cc", "durable"] },
};

characters.forEach((character) => {
  character.weapons = characterWeapons[character.id] ?? ["unknown"];
  character.image = `assets/characters/mini/${character.id}.png`;
  character.imageTemplates = [character.image, ...(skinTemplates[character.id] ?? [])];
});

export const characterVariants = characters.flatMap((character) =>
  character.weapons.map((weapon) => {
    const weaponType = weaponTypes[weapon] ?? weaponTypes.unknown;
    const override = variantOverrides[`${character.id}:${weapon}`] ?? {};
    const tags = override.tags ?? character.tags;
    return {
      ...character,
      ...override,
      variantId: `${character.id}:${weapon}`,
      characterId: character.id,
      weapon,
      weaponLabel: weaponType.label,
      weaponStyle: weaponType.style ?? "",
      weaponRange: weaponType.range,
      tags: [...new Set(tags)],
    };
  }),
);

export const synergyPairs = {
  "lenox:hart": 8.8,
  "lenox:rio": 8.4,
  "lenox:haze": 8.1,
  "hyunwoo:sissela": 8.0,
  "hyunwoo:aya": 7.6,
  "estelle:rio": 8.6,
  "estelle:hart": 8.2,
  "estelle:shoichi": 7.8,
  "hart:yuki": 7.9,
  "hart:cathy": 7.5,
  "aya:chiara": 7.7,
  "rio:yuki": 8.0,
  "sissela:jackie": 7.9,
  "haze:jackie": 7.8,
  "adriana:hyunwoo": 8.1,
  "theodore:jackie": 7.8,
  "theodore:chiara": 7.7,
};

export const roleNames = Object.fromEntries(roles.map((role) => [role.id, role.label]));
