// Generated by tools/pair_synergy_lift.mjs. Do not edit by hand.
export const pairSynergyLiftMeta = {
  "generatedAt": "2026-09-04T14:29:28.738Z",
  "source": "corpus.jsonl",
  "by": "char",
  "minSamples": 60,
  "fdr": 0.1,
  "scanLimit": null,
  "matchingMode": 3,
  "minSeason": 41,
  "scanned": 2765284,
  "teams": 539719,
  "pairs": 3664,
  "significantPairs": 161,
  "teamTier": "all"
};

export const officialPairSynergyLift = {
  "charlotte|leni": {
    "lift": -0.9723,
    "n": 68,
    "z": 3.955
  },
  "charlotte|laura": {
    "lift": -0.8916,
    "n": 65,
    "z": 3.601
  },
  "leni|lucia": {
    "lift": -0.8003,
    "n": 210,
    "z": 5.532
  },
  "istvan|zahir": {
    "lift": 0.7614,
    "n": 131,
    "z": -4.228
  },
  "aya|leni": {
    "lift": -0.649,
    "n": 97,
    "z": 3.222
  },
  "isol|zahir": {
    "lift": 0.6465,
    "n": 105,
    "z": -2.888
  },
  "charlotte|magnus": {
    "lift": -0.6462,
    "n": 122,
    "z": 3.321
  },
  "alonso|laura": {
    "lift": -0.622,
    "n": 142,
    "z": 3.276
  },
  "aya|jenny": {
    "lift": 0.5979,
    "n": 130,
    "z": -2.916
  },
  "eva|piolo": {
    "lift": 0.5961,
    "n": 164,
    "z": -3.201
  },
  "mirka|yan": {
    "lift": 0.5946,
    "n": 116,
    "z": -2.904
  },
  "cathy|zahir": {
    "lift": 0.5921,
    "n": 149,
    "z": -3.219
  },
  "justina|silvia": {
    "lift": 0.5813,
    "n": 142,
    "z": -3.029
  },
  "rozzi|tsubame": {
    "lift": -0.5801,
    "n": 118,
    "z": 2.948
  },
  "blair|charlotte": {
    "lift": -0.5774,
    "n": 198,
    "z": 3.542
  },
  "adina|elena": {
    "lift": 0.5755,
    "n": 130,
    "z": -2.851
  },
  "alonso|hyejin": {
    "lift": -0.5707,
    "n": 221,
    "z": 3.576
  },
  "bernice|celine": {
    "lift": 0.5466,
    "n": 178,
    "z": -3.216
  },
  "cathy|mirka": {
    "lift": 0.513,
    "n": 183,
    "z": -3.141
  },
  "henry|william": {
    "lift": 0.5117,
    "n": 210,
    "z": -3.128
  },
  "alex|chloe": {
    "lift": 0.5081,
    "n": 168,
    "z": -3.003
  },
  "alonso|luke": {
    "lift": -0.5038,
    "n": 207,
    "z": 3.206
  },
  "adela|nadine": {
    "lift": 0.5037,
    "n": 211,
    "z": -3.263
  },
  "chloe|eva": {
    "lift": 0.4983,
    "n": 150,
    "z": -2.867
  },
  "coreline|isol": {
    "lift": 0.4948,
    "n": 273,
    "z": -3.632
  },
  "eva|rozzi": {
    "lift": 0.4933,
    "n": 203,
    "z": -2.923
  },
  "charlotte|luke": {
    "lift": -0.4883,
    "n": 203,
    "z": 3.041
  },
  "adriana|emma": {
    "lift": 0.4856,
    "n": 220,
    "z": -3.148
  },
  "alex|william": {
    "lift": 0.4793,
    "n": 271,
    "z": -3.463
  },
  "chloe|jackie": {
    "lift": 0.4744,
    "n": 381,
    "z": -4.197
  },
  "charlotte|lucia": {
    "lift": -0.4723,
    "n": 397,
    "z": 4.099
  },
  "aya|daniel": {
    "lift": 0.445,
    "n": 472,
    "z": -4.189
  },
  "barbara|sho": {
    "lift": 0.4427,
    "n": 204,
    "z": -2.894
  },
  "blair|elena": {
    "lift": -0.4426,
    "n": 326,
    "z": 3.495
  },
  "silvia|sua": {
    "lift": 0.423,
    "n": 357,
    "z": -3.693
  },
  "blair|shoichi": {
    "lift": -0.4218,
    "n": 418,
    "z": 3.817
  },
  "alex|garnet": {
    "lift": 0.4189,
    "n": 323,
    "z": -3.488
  },
  "lucia|shoichi": {
    "lift": -0.4187,
    "n": 2056,
    "z": 8.631
  },
  "fenrir|laura": {
    "lift": -0.4129,
    "n": 374,
    "z": 3.537
  },
  "celine|leon": {
    "lift": 0.408,
    "n": 303,
    "z": -3.08
  },
  "daniel|rio": {
    "lift": 0.4045,
    "n": 315,
    "z": -3.042
  },
  "blair|katja": {
    "lift": -0.4019,
    "n": 644,
    "z": 4.464
  },
  "alonso|darko": {
    "lift": -0.4013,
    "n": 330,
    "z": 3.147
  },
  "elena|leon": {
    "lift": 0.4004,
    "n": 466,
    "z": -3.813
  },
  "alonso|rozzi": {
    "lift": -0.3943,
    "n": 389,
    "z": 3.356
  },
  "aiden|nadine": {
    "lift": 0.3927,
    "n": 323,
    "z": -2.992
  },
  "chloe|shirin": {
    "lift": 0.3927,
    "n": 388,
    "z": -3.415
  },
  "blair|luke": {
    "lift": -0.39,
    "n": 461,
    "z": 3.768
  },
  "garnet|zahir": {
    "lift": 0.3861,
    "n": 434,
    "z": -3.472
  },
  "eleven|zahir": {
    "lift": 0.3839,
    "n": 330,
    "z": -2.929
  },
  "blair|hisui": {
    "lift": -0.3805,
    "n": 533,
    "z": 3.833
  },
  "elena|william": {
    "lift": 0.3785,
    "n": 356,
    "z": -3.028
  },
  "lucia|mirka": {
    "lift": -0.3743,
    "n": 992,
    "z": 5.34
  },
  "barbara|nadine": {
    "lift": 0.3721,
    "n": 375,
    "z": -3.106
  },
  "lenox|shoichi": {
    "lift": -0.3709,
    "n": 408,
    "z": 3.37
  },
  "lenore|tsubame": {
    "lift": 0.3708,
    "n": 483,
    "z": -3.409
  },
  "abigail|kenneth": {
    "lift": -0.3628,
    "n": 499,
    "z": 3.55
  },
  "katja|silvia": {
    "lift": 0.3546,
    "n": 483,
    "z": -3.362
  },
  "bihyung|nicky": {
    "lift": -0.353,
    "n": 483,
    "z": 3.512
  },
  "adriana|rozzi": {
    "lift": 0.3527,
    "n": 422,
    "z": -3.182
  },
  "abigail|shoichi": {
    "lift": -0.3499,
    "n": 835,
    "z": 4.451
  },
  "adriana|yuki": {
    "lift": 0.3483,
    "n": 1530,
    "z": -6.063
  },
  "emma|jackie": {
    "lift": 0.3457,
    "n": 608,
    "z": -3.654
  },
  "adela|jackie": {
    "lift": 0.3452,
    "n": 466,
    "z": -3.248
  },
  "justina|lucia": {
    "lift": -0.343,
    "n": 636,
    "z": 3.893
  },
  "elena|rozzi": {
    "lift": 0.3406,
    "n": 525,
    "z": -3.458
  },
  "bihyung|luke": {
    "lift": -0.3386,
    "n": 490,
    "z": 3.317
  },
  "alex|rio": {
    "lift": 0.3299,
    "n": 540,
    "z": -3.354
  },
  "hisui|lucia": {
    "lift": -0.3296,
    "n": 2138,
    "z": 6.83
  },
  "aiden|shoichi": {
    "lift": -0.3287,
    "n": 626,
    "z": 3.693
  },
  "nicky|tia": {
    "lift": 0.3285,
    "n": 464,
    "z": -3.064
  },
  "lucia|tsubame": {
    "lift": -0.3235,
    "n": 906,
    "z": 4.374
  },
  "blair|sua": {
    "lift": -0.3221,
    "n": 491,
    "z": 3.085
  },
  "hisui|luke": {
    "lift": -0.3193,
    "n": 997,
    "z": 4.377
  },
  "piolo|tsubame": {
    "lift": 0.3184,
    "n": 474,
    "z": -3.067
  },
  "alex|aya": {
    "lift": 0.317,
    "n": 592,
    "z": -3.362
  },
  "nicky|shoichi": {
    "lift": -0.3144,
    "n": 1161,
    "z": 4.649
  },
  "barbara|hisui": {
    "lift": -0.3124,
    "n": 661,
    "z": 3.513
  },
  "barbara|rio": {
    "lift": 0.3094,
    "n": 719,
    "z": -3.504
  },
  "lucia|sua": {
    "lift": -0.3051,
    "n": 1813,
    "z": 5.821
  },
  "li_dailin|lucia": {
    "lift": -0.3029,
    "n": 1016,
    "z": 4.29
  },
  "hisui|katja": {
    "lift": -0.3019,
    "n": 2209,
    "z": 6.175
  },
  "coreline|lucia": {
    "lift": -0.2964,
    "n": 604,
    "z": 3.47
  },
  "lucia|magnus": {
    "lift": -0.295,
    "n": 2016,
    "z": 5.928
  },
  "ian|yuki": {
    "lift": 0.2932,
    "n": 526,
    "z": -3.053
  },
  "aya|henry": {
    "lift": 0.2929,
    "n": 644,
    "z": -3.212
  },
  "aya|piolo": {
    "lift": 0.292,
    "n": 583,
    "z": -3.071
  },
  "istvan|shoichi": {
    "lift": -0.2913,
    "n": 498,
    "z": 2.983
  },
  "hisui|hyunwoo": {
    "lift": -0.2896,
    "n": 527,
    "z": 2.914
  },
  "alonso|jackie": {
    "lift": -0.2896,
    "n": 561,
    "z": 2.929
  },
  "lucia|yumin": {
    "lift": -0.2875,
    "n": 997,
    "z": 4.085
  },
  "celine|yuki": {
    "lift": 0.286,
    "n": 555,
    "z": -2.947
  },
  "hisui|nadine": {
    "lift": -0.2856,
    "n": 647,
    "z": 3.183
  },
  "bianca|lucia": {
    "lift": -0.2855,
    "n": 791,
    "z": 3.602
  },
  "leon|yuki": {
    "lift": 0.2833,
    "n": 1221,
    "z": -4.354
  },
  "alex|jackie": {
    "lift": 0.2824,
    "n": 707,
    "z": -3.411
  },
  "blair|lucia": {
    "lift": -0.2796,
    "n": 791,
    "z": 3.54
  },
  "adriana|leon": {
    "lift": 0.2782,
    "n": 845,
    "z": -3.55
  },
  "hisui|shoichi": {
    "lift": -0.2757,
    "n": 1036,
    "z": 3.894
  },
  "shoichi|yan": {
    "lift": -0.2749,
    "n": 675,
    "z": 3.162
  },
  "craver|lucia": {
    "lift": -0.2723,
    "n": 2007,
    "z": 5.57
  },
  "lucia|luke": {
    "lift": -0.2722,
    "n": 1877,
    "z": 5.314
  },
  "bianca|garnet": {
    "lift": -0.272,
    "n": 649,
    "z": 3.16
  },
  "lucia|yan": {
    "lift": -0.2704,
    "n": 983,
    "z": 3.857
  },
  "luke|shoichi": {
    "lift": -0.2699,
    "n": 988,
    "z": 3.59
  },
  "elena|jackie": {
    "lift": 0.2665,
    "n": 1217,
    "z": -4.086
  },
  "bihyung|shoichi": {
    "lift": -0.2656,
    "n": 699,
    "z": 3.039
  },
  "hisui|justina": {
    "lift": -0.263,
    "n": 648,
    "z": 2.956
  },
  "lucia|nia": {
    "lift": -0.262,
    "n": 899,
    "z": 3.538
  },
  "lucia|nicky": {
    "lift": -0.2611,
    "n": 2231,
    "z": 5.416
  },
  "bianca|hisui": {
    "lift": -0.2583,
    "n": 1016,
    "z": 3.54
  },
  "darko|lucia": {
    "lift": -0.2579,
    "n": 3300,
    "z": 6.663
  },
  "fenrir|nicky": {
    "lift": -0.2557,
    "n": 914,
    "z": 3.468
  },
  "aya|barbara": {
    "lift": 0.2549,
    "n": 722,
    "z": -2.953
  },
  "bihyung|lucia": {
    "lift": -0.2539,
    "n": 1586,
    "z": 4.583
  },
  "henry|katja": {
    "lift": 0.2483,
    "n": 1254,
    "z": -3.709
  },
  "haze|leon": {
    "lift": 0.2455,
    "n": 985,
    "z": -3.376
  },
  "justina|katja": {
    "lift": 0.2413,
    "n": 1086,
    "z": -3.402
  },
  "shirin|shoichi": {
    "lift": -0.238,
    "n": 1048,
    "z": 3.454
  },
  "katja|sissela": {
    "lift": 0.2378,
    "n": 888,
    "z": -3.002
  },
  "abigail|hisui": {
    "lift": -0.2369,
    "n": 1189,
    "z": 3.548
  },
  "abigail|adriana": {
    "lift": 0.2345,
    "n": 937,
    "z": -3.118
  },
  "haze|hisui": {
    "lift": -0.2279,
    "n": 1173,
    "z": 3.384
  },
  "katja|lucia": {
    "lift": -0.2243,
    "n": 1999,
    "z": 4.391
  },
  "hisui|nicky": {
    "lift": -0.2231,
    "n": 1231,
    "z": 3.422
  },
  "isaac|lucia": {
    "lift": -0.2207,
    "n": 942,
    "z": 3.02
  },
  "alonso|rio": {
    "lift": -0.2202,
    "n": 1048,
    "z": 2.99
  },
  "garnet|leon": {
    "lift": 0.2188,
    "n": 897,
    "z": -2.943
  },
  "adriana|sua": {
    "lift": 0.2187,
    "n": 1100,
    "z": -3.257
  },
  "abigail|lucia": {
    "lift": -0.2175,
    "n": 1699,
    "z": 4.009
  },
  "bihyung|hisui": {
    "lift": -0.216,
    "n": 995,
    "z": 3.036
  },
  "hisui|yumin": {
    "lift": -0.2152,
    "n": 1186,
    "z": 3.234
  },
  "fenrir|hisui": {
    "lift": -0.2146,
    "n": 907,
    "z": 2.875
  },
  "eleven|lucia": {
    "lift": -0.2143,
    "n": 1599,
    "z": 3.768
  },
  "lucia|shirin": {
    "lift": -0.2141,
    "n": 1981,
    "z": 4.403
  },
  "adriana|jackie": {
    "lift": 0.2134,
    "n": 1343,
    "z": -3.508
  },
  "abigail|shirin": {
    "lift": -0.2123,
    "n": 1177,
    "z": 3.226
  },
  "adriana|magnus": {
    "lift": 0.2097,
    "n": 1110,
    "z": -3.066
  },
  "adriana|darko": {
    "lift": 0.2093,
    "n": 1650,
    "z": -3.713
  },
  "debi_marlene|hisui": {
    "lift": -0.2089,
    "n": 1209,
    "z": 3.171
  },
  "debi_marlene|lucia": {
    "lift": -0.2081,
    "n": 2139,
    "z": 4.262
  },
  "abigail|darko": {
    "lift": -0.2068,
    "n": 1395,
    "z": 3.38
  },
  "katja|shirin": {
    "lift": -0.2062,
    "n": 2225,
    "z": 4.279
  },
  "aya|yuki": {
    "lift": 0.2053,
    "n": 2436,
    "z": -4.435
  },
  "hisui|rio": {
    "lift": -0.2024,
    "n": 1120,
    "z": 2.992
  },
  "jackie|shoichi": {
    "lift": -0.2021,
    "n": 1153,
    "z": 2.953
  },
  "adriana|shirin": {
    "lift": 0.2005,
    "n": 1264,
    "z": -3.13
  },
  "katja|shoichi": {
    "lift": -0.1997,
    "n": 1234,
    "z": 3.098
  },
  "darko|hisui": {
    "lift": -0.1971,
    "n": 1716,
    "z": 3.478
  },
  "lucia|rio": {
    "lift": -0.197,
    "n": 1149,
    "z": 2.855
  },
  "haze|yuki": {
    "lift": 0.1968,
    "n": 1800,
    "z": -3.666
  },
  "craver|leon": {
    "lift": 0.196,
    "n": 2848,
    "z": -4.681
  },
  "hisui|shirin": {
    "lift": -0.1913,
    "n": 1402,
    "z": 3.191
  },
  "garnet|lucia": {
    "lift": -0.1846,
    "n": 2998,
    "z": 4.672
  },
  "lenox|lucia": {
    "lift": -0.1793,
    "n": 1790,
    "z": 3.351
  },
  "fenrir|lucia": {
    "lift": -0.1767,
    "n": 1590,
    "z": 3.156
  },
  "katja|luke": {
    "lift": -0.1719,
    "n": 1552,
    "z": 2.901
  },
  "aya|jackie": {
    "lift": 0.1713,
    "n": 1689,
    "z": -3.094
  },
  "katja|sua": {
    "lift": -0.1515,
    "n": 2246,
    "z": 3.142
  },
  "lucia|yuki": {
    "lift": -0.1383,
    "n": 3172,
    "z": 3.451
  },
  "darko|katja": {
    "lift": -0.1009,
    "n": 4368,
    "z": 2.887
  }
};
