// Generated by tools/pair_synergy_lift.mjs. Do not edit by hand.
export const pairSynergyLiftMeta = {
  "generatedAt": "2026-06-21T15:35:25.425Z",
  "source": "matches-current-20260617T051948Z.jsonl",
  "by": "char",
  "minSamples": 40,
  "fdr": 0.1,
  "scanLimit": 200000,
  "scanned": 110449,
  "teams": 110449,
  "pairs": 2663,
  "significantPairs": 73,
  "teamTier": "all"
};

export const officialPairSynergyLift = {
  "aiden|zahir": {
    "lift": 1.0899,
    "n": 52,
    "z": -3.636
  },
  "eleven|nathapon": {
    "lift": 1.0392,
    "n": 48,
    "z": -3.388
  },
  "aya|charlotte": {
    "lift": 1.0186,
    "n": 59,
    "z": -3.304
  },
  "lenox|nathapon": {
    "lift": -1.0169,
    "n": 56,
    "z": 3.463
  },
  "alex|tazia": {
    "lift": 0.9684,
    "n": 56,
    "z": -3.674
  },
  "kenneth|markus": {
    "lift": -0.8512,
    "n": 144,
    "z": 4.897
  },
  "darko|zahir": {
    "lift": 0.8494,
    "n": 83,
    "z": -3.568
  },
  "charlotte|luke": {
    "lift": -0.838,
    "n": 145,
    "z": 4.628
  },
  "bianca|kenneth": {
    "lift": -0.8159,
    "n": 194,
    "z": 5.376
  },
  "leon|sua": {
    "lift": 0.8024,
    "n": 65,
    "z": -3.175
  },
  "kenneth|sua": {
    "lift": -0.7829,
    "n": 142,
    "z": 4.36
  },
  "aya|bianca": {
    "lift": 0.7803,
    "n": 97,
    "z": -3.43
  },
  "debi_marlene|emma": {
    "lift": -0.7642,
    "n": 215,
    "z": 5.333
  },
  "rio|rozzi": {
    "lift": -0.7556,
    "n": 156,
    "z": 4.873
  },
  "bianca|charlotte": {
    "lift": -0.7398,
    "n": 160,
    "z": 4.884
  },
  "charlotte|shoichi": {
    "lift": -0.7366,
    "n": 184,
    "z": 4.802
  },
  "estelle|nathapon": {
    "lift": 0.7231,
    "n": 78,
    "z": -3.226
  },
  "abigail|kenneth": {
    "lift": -0.7209,
    "n": 235,
    "z": 5.241
  },
  "garnet|markus": {
    "lift": -0.7198,
    "n": 151,
    "z": 4.631
  },
  "katja|rozzi": {
    "lift": -0.7112,
    "n": 170,
    "z": 4.562
  },
  "katja|tsubame": {
    "lift": -0.6913,
    "n": 154,
    "z": 4.047
  },
  "garnet|tia": {
    "lift": 0.6743,
    "n": 133,
    "z": -3.531
  },
  "rozzi|shoichi": {
    "lift": -0.6732,
    "n": 236,
    "z": 4.929
  },
  "alonso|theodore": {
    "lift": -0.6644,
    "n": 169,
    "z": 3.575
  },
  "katja|rio": {
    "lift": -0.6626,
    "n": 147,
    "z": 3.772
  },
  "bianca|sissela": {
    "lift": -0.6525,
    "n": 146,
    "z": 3.87
  },
  "abigail|nathapon": {
    "lift": 0.646,
    "n": 112,
    "z": -3.004
  },
  "kenneth|rozzi": {
    "lift": -0.6455,
    "n": 172,
    "z": 4.126
  },
  "shoichi|tsubame": {
    "lift": -0.6398,
    "n": 249,
    "z": 4.776
  },
  "abigail|charlotte": {
    "lift": -0.6391,
    "n": 198,
    "z": 4.372
  },
  "bianca|emma": {
    "lift": -0.6308,
    "n": 167,
    "z": 3.951
  },
  "charlotte|garnet": {
    "lift": -0.6171,
    "n": 158,
    "z": 3.682
  },
  "aya|cathy": {
    "lift": 0.6007,
    "n": 122,
    "z": -3.058
  },
  "luke|rozzi": {
    "lift": -0.5998,
    "n": 231,
    "z": 4.535
  },
  "kenneth|rio": {
    "lift": -0.5945,
    "n": 211,
    "z": 3.923
  },
  "kenneth|vanya": {
    "lift": -0.5921,
    "n": 195,
    "z": 3.813
  },
  "garnet|sua": {
    "lift": -0.5891,
    "n": 210,
    "z": 4.056
  },
  "kenneth|sissela": {
    "lift": -0.5841,
    "n": 173,
    "z": 3.603
  },
  "emma|kenneth": {
    "lift": -0.5837,
    "n": 174,
    "z": 3.605
  },
  "emma|markus": {
    "lift": -0.5794,
    "n": 189,
    "z": 3.825
  },
  "kenneth|shoichi": {
    "lift": -0.5751,
    "n": 204,
    "z": 4.16
  },
  "charlotte|rozzi": {
    "lift": -0.5747,
    "n": 138,
    "z": 3.269
  },
  "emma|tsubame": {
    "lift": -0.5734,
    "n": 208,
    "z": 3.717
  },
  "charlotte|sissela": {
    "lift": -0.5716,
    "n": 149,
    "z": 3.602
  },
  "emma|rozzi": {
    "lift": -0.5652,
    "n": 174,
    "z": 3.523
  },
  "estelle|isol": {
    "lift": 0.5635,
    "n": 187,
    "z": -3.575
  },
  "garnet|kenneth": {
    "lift": -0.5608,
    "n": 183,
    "z": 3.712
  },
  "kenneth|leni": {
    "lift": 0.5536,
    "n": 259,
    "z": -3.832
  },
  "coreline|yuki": {
    "lift": -0.5471,
    "n": 162,
    "z": 3.036
  },
  "charlotte|kenneth": {
    "lift": -0.5468,
    "n": 161,
    "z": 3.365
  },
  "haze|nadine": {
    "lift": 0.5286,
    "n": 148,
    "z": -3.064
  },
  "kenneth|yuki": {
    "lift": -0.5266,
    "n": 173,
    "z": 3.235
  },
  "abigail|shoichi": {
    "lift": -0.5203,
    "n": 342,
    "z": 4.291
  },
  "luke|sissela": {
    "lift": -0.5166,
    "n": 200,
    "z": 3.513
  },
  "garnet|yuki": {
    "lift": -0.5033,
    "n": 265,
    "z": 3.858
  },
  "charlotte|tsubame": {
    "lift": -0.5023,
    "n": 134,
    "z": 3.011
  },
  "rozzi|sissela": {
    "lift": -0.4931,
    "n": 196,
    "z": 3.373
  },
  "rozzi|vanya": {
    "lift": -0.4917,
    "n": 230,
    "z": 3.428
  },
  "debi_marlene|rozzi": {
    "lift": -0.4893,
    "n": 244,
    "z": 3.464
  },
  "rio|shoichi": {
    "lift": -0.4858,
    "n": 206,
    "z": 3.209
  },
  "lenore|yuki": {
    "lift": 0.4735,
    "n": 230,
    "z": -3.038
  },
  "debi_marlene|luke": {
    "lift": -0.4653,
    "n": 270,
    "z": 3.41
  },
  "debi_marlene|sua": {
    "lift": -0.4631,
    "n": 202,
    "z": 3.055
  },
  "garnet|sissela": {
    "lift": -0.4511,
    "n": 314,
    "z": 3.635
  },
  "debi_marlene|shoichi": {
    "lift": -0.4401,
    "n": 323,
    "z": 3.473
  },
  "garnet|isol": {
    "lift": 0.4237,
    "n": 269,
    "z": -3.13
  },
  "shoichi|yuki": {
    "lift": -0.4223,
    "n": 325,
    "z": 3.328
  },
  "abigail|markus": {
    "lift": -0.4041,
    "n": 279,
    "z": 3.063
  },
  "abigail|rozzi": {
    "lift": -0.3789,
    "n": 300,
    "z": 3.022
  },
  "bihyung|haze": {
    "lift": 0.3644,
    "n": 461,
    "z": -3.363
  },
  "garnet|rio": {
    "lift": -0.3469,
    "n": 470,
    "z": 3.325
  },
  "abigail|katja": {
    "lift": -0.3156,
    "n": 517,
    "z": 3.099
  },
  "aya|garnet": {
    "lift": 0.2985,
    "n": 494,
    "z": -3.011
  }
};
