// AUTO-GENERATED by tools/build_tournament_meta.mjs. Do not edit by hand.
// Source: 22 tournament games from tournament_s41.json
// Season filter: >= 41
// Generated: 2026-09-05T09:05:44.618Z
// 39 compositions with 2+ appearances

export const tournamentTotalGames = 22;

// Per-character pick/win/top3 counts (string IDs matching characterVariants)
export const tournamentCharStats = {
  "nadine": {
    "picks": 12,
    "wins": 1,
    "top3": 3
  },
  "priya": {
    "picks": 15,
    "wins": 4,
    "top3": 7
  },
  "yumin": {
    "picks": 7,
    "wins": 1,
    "top3": 2
  },
  "adela": {
    "picks": 21,
    "wins": 1,
    "top3": 6
  },
  "eva": {
    "picks": 14,
    "wins": 1,
    "top3": 8
  },
  "chloe": {
    "picks": 12,
    "wins": 0,
    "top3": 6
  },
  "emma": {
    "picks": 17,
    "wins": 2,
    "top3": 6
  },
  "daniel": {
    "picks": 14,
    "wins": 2,
    "top3": 6
  },
  "abigail": {
    "picks": 14,
    "wins": 2,
    "top3": 6
  },
  "hyejin": {
    "picks": 4,
    "wins": 0,
    "top3": 2
  },
  "sua": {
    "picks": 22,
    "wins": 3,
    "top3": 10
  },
  "nicky": {
    "picks": 14,
    "wins": 0,
    "top3": 5
  },
  "haze": {
    "picks": 8,
    "wins": 1,
    "top3": 4
  },
  "mirka": {
    "picks": 8,
    "wins": 1,
    "top3": 4
  },
  "craver": {
    "picks": 12,
    "wins": 1,
    "top3": 4
  },
  "celine": {
    "picks": 3,
    "wins": 0,
    "top3": 0
  },
  "jackie": {
    "picks": 29,
    "wins": 6,
    "top3": 8
  },
  "mai": {
    "picks": 10,
    "wins": 0,
    "top3": 1
  },
  "martina": {
    "picks": 4,
    "wins": 0,
    "top3": 0
  },
  "adriana": {
    "picks": 10,
    "wins": 0,
    "top3": 2
  },
  "bernice": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "karla": {
    "picks": 8,
    "wins": 1,
    "top3": 5
  },
  "garnet": {
    "picks": 2,
    "wins": 0,
    "top3": 1
  },
  "sissela": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "rozzi": {
    "picks": 14,
    "wins": 2,
    "top3": 2
  },
  "alex": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "william": {
    "picks": 8,
    "wins": 0,
    "top3": 2
  },
  "justina": {
    "picks": 15,
    "wins": 2,
    "top3": 7
  },
  "barbara": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "yan": {
    "picks": 13,
    "wins": 4,
    "top3": 7
  },
  "tazia": {
    "picks": 13,
    "wins": 6,
    "top3": 9
  },
  "isaac": {
    "picks": 8,
    "wins": 0,
    "top3": 3
  },
  "li_dailin": {
    "picks": 2,
    "wins": 0,
    "top3": 1
  },
  "cathy": {
    "picks": 8,
    "wins": 0,
    "top3": 0
  },
  "markus": {
    "picks": 25,
    "wins": 5,
    "top3": 10
  },
  "arda": {
    "picks": 3,
    "wins": 0,
    "top3": 1
  },
  "eleven": {
    "picks": 4,
    "wins": 0,
    "top3": 0
  },
  "laura": {
    "picks": 4,
    "wins": 0,
    "top3": 0
  },
  "bianca": {
    "picks": 8,
    "wins": 1,
    "top3": 1
  },
  "elena": {
    "picks": 18,
    "wins": 7,
    "top3": 7
  },
  "felix": {
    "picks": 4,
    "wins": 0,
    "top3": 2
  },
  "debi_marlene": {
    "picks": 4,
    "wins": 0,
    "top3": 2
  },
  "charlotte": {
    "picks": 4,
    "wins": 0,
    "top3": 2
  },
  "aiden": {
    "picks": 19,
    "wins": 1,
    "top3": 3
  },
  "fenrir": {
    "picks": 6,
    "wins": 0,
    "top3": 0
  },
  "silvia": {
    "picks": 12,
    "wins": 0,
    "top3": 9
  },
  "zahir": {
    "picks": 1,
    "wins": 0,
    "top3": 1
  },
  "rio": {
    "picks": 10,
    "wins": 2,
    "top3": 6
  },
  "shirin": {
    "picks": 3,
    "wins": 0,
    "top3": 0
  },
  "vanya": {
    "picks": 4,
    "wins": 0,
    "top3": 0
  },
  "kenneth": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "darko": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "alonso": {
    "picks": 6,
    "wins": 1,
    "top3": 3
  },
  "estelle": {
    "picks": 11,
    "wins": 6,
    "top3": 7
  },
  "magnus": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "isol": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "piolo": {
    "picks": 11,
    "wins": 0,
    "top3": 7
  },
  "theodore": {
    "picks": 5,
    "wins": 1,
    "top3": 2
  },
  "luke": {
    "picks": 10,
    "wins": 0,
    "top3": 7
  },
  "nia": {
    "picks": 3,
    "wins": 1,
    "top3": 1
  }
};

export const tournamentCompositions = [
  {"members":["abigail","daniel","emma"],"appearances":14,"rank":4.36,"ts":4.21,"ks":8.29},
  {"members":["elena","estelle","jackie"],"appearances":10,"rank":2.8,"ts":7,"ks":8.65},
  {"members":["luke","piolo","silvia"],"appearances":10,"rank":3.4,"ts":4.9,"ks":10.15},
  {"members":["craver","haze","mirka"],"appearances":8,"rank":3.63,"ts":5.13,"ks":6.94},
  {"members":["bianca","elena","rozzi"],"appearances":8,"rank":5,"ts":3.38,"ks":7.75},
  {"members":["justina","markus","rio"],"appearances":6,"rank":3.83,"ts":5,"ks":7.67},
  {"members":["adela","chloe","eva"],"appearances":6,"rank":4,"ts":4.33,"ks":6.33},
  {"members":["chloe","eva","karla"],"appearances":6,"rank":4.17,"ts":4,"ks":7.58},
  {"members":["adriana","isaac","jackie"],"appearances":6,"rank":4.83,"ts":3.33,"ks":6.17},
  {"members":["aiden","fenrir","jackie"],"appearances":6,"rank":5.5,"ts":2.5,"ks":7.33},
  {"members":["markus","sua","tazia"],"appearances":5,"rank":2,"ts":8,"ks":10.9},
  {"members":["justina","mai","william"],"appearances":5,"rank":5.4,"ts":2.6,"ks":7.1},
  {"members":["nadine","priya","yumin"],"appearances":4,"rank":3.25,"ts":5.5,"ks":8.75},
  {"members":["aiden","markus","theodore"],"appearances":4,"rank":3.75,"ts":5,"ks":6.63},
  {"members":["charlotte","debi_marlene","felix"],"appearances":4,"rank":4,"ts":4.5,"ks":6.5},
  {"members":["alonso","justina","rio"],"appearances":4,"rank":4,"ts":5,"ks":8.25},
  {"members":["hyejin","nicky","sua"],"appearances":4,"rank":4.25,"ts":3.75,"ks":6.5},
  {"members":["cathy","eleven","laura"],"appearances":4,"rank":5.75,"ts":2.25,"ks":7.5},
  {"members":["priya","tazia","yan"],"appearances":3,"rank":1,"ts":10,"ks":9.33},
  {"members":["adela","nicky","sua"],"appearances":3,"rank":5,"ts":3,"ks":8.67},
  {"members":["jackie","mai","martina"],"appearances":3,"rank":5.33,"ts":2.67,"ks":4.83},
  {"members":["adela","nadine","shirin"],"appearances":3,"rank":5.33,"ts":2.67,"ks":5.17},
  {"members":["celine","emma","nadine"],"appearances":3,"rank":5.67,"ts":2.33,"ks":7.33},
  {"members":["adela","eva","karla"],"appearances":2,"rank":1.5,"ts":8.5,"ks":14},
  {"members":["nicky","silvia","sua"],"appearances":2,"rank":3,"ts":5,"ks":9},
  {"members":["alonso","tazia","william"],"appearances":2,"rank":3.5,"ts":4.5,"ks":3.5},
  {"members":["nia","rozzi","yan"],"appearances":2,"rank":4.5,"ts":5,"ks":11.25},
  {"members":["aiden","rozzi","yan"],"appearances":2,"rank":5,"ts":3,"ks":3.75},
  {"members":["aiden","markus","priya"],"appearances":2,"rank":5,"ts":3,"ks":6.75},
  {"members":["li_dailin","nicky","sua"],"appearances":2,"rank":5.5,"ts":2.5,"ks":6.25},
  {"members":["arda","cathy","markus"],"appearances":2,"rank":5.5,"ts":2.5,"ks":3.5},
  {"members":["craver","darko","vanya"],"appearances":2,"rank":6,"ts":2,"ks":8.5},
  {"members":["magnus","sua","tazia"],"appearances":2,"rank":6,"ts":2,"ks":2.5},
  {"members":["craver","kenneth","vanya"],"appearances":2,"rank":7,"ts":1,"ks":10.5},
  {"members":["adela","aiden","nicky"],"appearances":2,"rank":7,"ts":1,"ks":6},
  {"members":["markus","priya","yumin"],"appearances":2,"rank":7,"ts":1,"ks":4.25},
  {"members":["adela","adriana","bernice"],"appearances":2,"rank":8,"ts":0,"ks":2.75},
  {"members":["cathy","markus","sua"],"appearances":2,"rank":8,"ts":0,"ks":6},
  {"members":["adriana","jackie","mai"],"appearances":2,"rank":8,"ts":0,"ks":3.5},
];
