// AUTO-GENERATED by tools/tournament_collector.mjs
// Last updated: 2026-06-10
// Source: 79 tournament games (IDs 6755-6963)
// 121 compositions with 2+ appearances

export const tournamentTotalGames = 79;

// Per-character pick/win/top3 counts (string IDs matching characterVariants)
export const tournamentCharStats = {
  "nadine": {
    "picks": 57,
    "wins": 11,
    "top3": 22
  },
  "emma": {
    "picks": 74,
    "wins": 12,
    "top3": 29
  },
  "sua": {
    "picks": 44,
    "wins": 9,
    "top3": 25
  },
  "eva": {
    "picks": 33,
    "wins": 7,
    "top3": 13
  },
  "chloe": {
    "picks": 34,
    "wins": 7,
    "top3": 16
  },
  "karla": {
    "picks": 53,
    "wins": 12,
    "top3": 23
  },
  "johann": {
    "picks": 83,
    "wins": 7,
    "top3": 34
  },
  "vanya": {
    "picks": 14,
    "wins": 0,
    "top3": 8
  },
  "garnet": {
    "picks": 32,
    "wins": 3,
    "top3": 13
  },
  "hart": {
    "picks": 61,
    "wins": 8,
    "top3": 21
  },
  "adela": {
    "picks": 16,
    "wins": 2,
    "top3": 7
  },
  "coreline": {
    "picks": 44,
    "wins": 9,
    "top3": 17
  },
  "celine": {
    "picks": 19,
    "wins": 1,
    "top3": 4
  },
  "markus": {
    "picks": 59,
    "wins": 8,
    "top3": 24
  },
  "martina": {
    "picks": 8,
    "wins": 0,
    "top3": 1
  },
  "irem": {
    "picks": 18,
    "wins": 3,
    "top3": 7
  },
  "silvia": {
    "picks": 56,
    "wins": 6,
    "top3": 20
  },
  "priya": {
    "picks": 22,
    "wins": 6,
    "top3": 9
  },
  "kenneth": {
    "picks": 13,
    "wins": 1,
    "top3": 3
  },
  "sho": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "sissela": {
    "picks": 31,
    "wins": 3,
    "top3": 8
  },
  "rio": {
    "picks": 10,
    "wins": 2,
    "top3": 3
  },
  "tazia": {
    "picks": 28,
    "wins": 0,
    "top3": 9
  },
  "arda": {
    "picks": 61,
    "wins": 3,
    "top3": 18
  },
  "alonso": {
    "picks": 46,
    "wins": 3,
    "top3": 15
  },
  "nia": {
    "picks": 61,
    "wins": 5,
    "top3": 20
  },
  "jenny": {
    "picks": 31,
    "wins": 7,
    "top3": 18
  },
  "aiden": {
    "picks": 15,
    "wins": 4,
    "top3": 9
  },
  "luke": {
    "picks": 16,
    "wins": 3,
    "top3": 4
  },
  "piolo": {
    "picks": 52,
    "wins": 5,
    "top3": 16
  },
  "isol": {
    "picks": 8,
    "wins": 1,
    "top3": 2
  },
  "abigail": {
    "picks": 47,
    "wins": 1,
    "top3": 11
  },
  "theodore": {
    "picks": 26,
    "wins": 1,
    "top3": 7
  },
  "rozzi": {
    "picks": 46,
    "wins": 8,
    "top3": 18
  },
  "eleven": {
    "picks": 8,
    "wins": 1,
    "top3": 4
  },
  "daniel": {
    "picks": 23,
    "wins": 0,
    "top3": 6
  },
  "camilo": {
    "picks": 14,
    "wins": 1,
    "top3": 2
  },
  "tia": {
    "picks": 8,
    "wins": 0,
    "top3": 0
  },
  "yan": {
    "picks": 32,
    "wins": 3,
    "top3": 10
  },
  "cathy": {
    "picks": 14,
    "wins": 1,
    "top3": 6
  },
  "felix": {
    "picks": 8,
    "wins": 1,
    "top3": 3
  },
  "fiora": {
    "picks": 46,
    "wins": 7,
    "top3": 22
  },
  "tsubame": {
    "picks": 41,
    "wins": 5,
    "top3": 18
  },
  "justina": {
    "picks": 47,
    "wins": 7,
    "top3": 17
  },
  "yumin": {
    "picks": 27,
    "wins": 4,
    "top3": 12
  },
  "shoichi": {
    "picks": 14,
    "wins": 3,
    "top3": 7
  },
  "mai": {
    "picks": 43,
    "wins": 7,
    "top3": 20
  },
  "haze": {
    "picks": 31,
    "wins": 1,
    "top3": 10
  },
  "mirka": {
    "picks": 5,
    "wins": 0,
    "top3": 3
  },
  "alex": {
    "picks": 2,
    "wins": 0,
    "top3": 1
  },
  "zahir": {
    "picks": 11,
    "wins": 2,
    "top3": 5
  },
  "adriana": {
    "picks": 14,
    "wins": 3,
    "top3": 6
  },
  "bernice": {
    "picks": 9,
    "wins": 2,
    "top3": 4
  },
  "nicky": {
    "picks": 29,
    "wins": 1,
    "top3": 10
  },
  "bianca": {
    "picks": 20,
    "wins": 3,
    "top3": 9
  },
  "katja": {
    "picks": 32,
    "wins": 3,
    "top3": 11
  },
  "leni": {
    "picks": 29,
    "wins": 8,
    "top3": 12
  },
  "william": {
    "picks": 18,
    "wins": 2,
    "top3": 7
  },
  "blair": {
    "picks": 4,
    "wins": 0,
    "top3": 1
  },
  "laura": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "charlotte": {
    "picks": 11,
    "wins": 3,
    "top3": 9
  },
  "istvan": {
    "picks": 18,
    "wins": 1,
    "top3": 6
  },
  "debi_marlene": {
    "picks": 14,
    "wins": 0,
    "top3": 3
  },
  "lenore": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "adina": {
    "picks": 5,
    "wins": 1,
    "top3": 2
  },
  "echion": {
    "picks": 18,
    "wins": 4,
    "top3": 10
  },
  "estelle": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "magnus": {
    "picks": 9,
    "wins": 0,
    "top3": 1
  },
  "hyunwoo": {
    "picks": 3,
    "wins": 1,
    "top3": 2
  },
  "yuki": {
    "picks": 2,
    "wins": 0,
    "top3": 1
  },
  "hyejin": {
    "picks": 9,
    "wins": 0,
    "top3": 2
  },
  "lenox": {
    "picks": 5,
    "wins": 1,
    "top3": 1
  },
  "jackie": {
    "picks": 5,
    "wins": 0,
    "top3": 1
  },
  "li_dailin": {
    "picks": 20,
    "wins": 1,
    "top3": 6
  },
  "chiara": {
    "picks": 6,
    "wins": 1,
    "top3": 2
  },
  "barbara": {
    "picks": 2,
    "wins": 0,
    "top3": 0
  },
  "elena": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "darko": {
    "picks": 2,
    "wins": 0,
    "top3": 1
  },
  "shirin": {
    "picks": 1,
    "wins": 0,
    "top3": 0
  },
  "hisui": {
    "picks": 2,
    "wins": 0,
    "top3": 2
  },
  "henry": {
    "picks": 4,
    "wins": 0,
    "top3": 1
  },
  "bihyung": {
    "picks": 6,
    "wins": 1,
    "top3": 1
  }
};

// Compositions seen 2+ times — members are string character IDs
export const tournamentCompositions = [
  {
    "members": [
      "chloe",
      "eva",
      "karla"
    ],
    "appearances": 27,
    "rank": 3.78,
    "ts": 5.19,
    "ks": 9.41
  },
  {
    "members": [
      "abigail",
      "daniel",
      "emma"
    ],
    "appearances": 22,
    "rank": 5.18,
    "ts": 2.91,
    "ks": 8.64
  },
  {
    "members": [
      "jenny",
      "johann",
      "justina"
    ],
    "appearances": 21,
    "rank": 3.86,
    "ts": 5.14,
    "ks": 7.88
  },
  {
    "members": [
      "fiora",
      "markus",
      "silvia"
    ],
    "appearances": 19,
    "rank": 4,
    "ts": 4.63,
    "ks": 8.5
  },
  {
    "members": [
      "emma",
      "nadine",
      "sua"
    ],
    "appearances": 16,
    "rank": 3.06,
    "ts": 6.44,
    "ks": 8.16
  },
  {
    "members": [
      "li_dailin",
      "nia",
      "rozzi"
    ],
    "appearances": 14,
    "rank": 4.21,
    "ts": 4.14,
    "ks": 7.32
  },
  {
    "members": [
      "garnet",
      "johann",
      "vanya"
    ],
    "appearances": 11,
    "rank": 3.73,
    "ts": 4.36,
    "ks": 6.09
  },
  {
    "members": [
      "johann",
      "sua",
      "yumin"
    ],
    "appearances": 11,
    "rank": 3.82,
    "ts": 4.64,
    "ks": 6.09
  },
  {
    "members": [
      "arda",
      "istvan",
      "piolo"
    ],
    "appearances": 11,
    "rank": 4.45,
    "ts": 3.91,
    "ks": 8.36
  },
  {
    "members": [
      "alonso",
      "nia",
      "tsubame"
    ],
    "appearances": 11,
    "rank": 4.64,
    "ts": 3.73,
    "ks": 7.18
  },
  {
    "members": [
      "adriana",
      "echion",
      "tsubame"
    ],
    "appearances": 11,
    "rank": 3.91,
    "ts": 5.09,
    "ks": 8.64
  },
  {
    "members": [
      "luke",
      "piolo",
      "silvia"
    ],
    "appearances": 10,
    "rank": 4.6,
    "ts": 4.1,
    "ks": 8.3
  },
  {
    "members": [
      "arda",
      "cathy",
      "markus"
    ],
    "appearances": 10,
    "rank": 3,
    "ts": 5.7,
    "ks": 6.1
  },
  {
    "members": [
      "garnet",
      "leni",
      "yumin"
    ],
    "appearances": 10,
    "rank": 3.9,
    "ts": 5,
    "ks": 7.15
  },
  {
    "members": [
      "alonso",
      "nadine",
      "nia"
    ],
    "appearances": 10,
    "rank": 5.6,
    "ts": 2.4,
    "ks": 7.9
  },
  {
    "members": [
      "emma",
      "piolo",
      "silvia"
    ],
    "appearances": 9,
    "rank": 4.33,
    "ts": 4.22,
    "ks": 8.56
  },
  {
    "members": [
      "abigail",
      "celine",
      "isol"
    ],
    "appearances": 8,
    "rank": 5.38,
    "ts": 3.13,
    "ks": 7.5
  },
  {
    "members": [
      "haze",
      "mai",
      "shoichi"
    ],
    "appearances": 8,
    "rank": 4.75,
    "ts": 3.38,
    "ks": 5.88
  },
  {
    "members": [
      "camilo",
      "magnus",
      "silvia"
    ],
    "appearances": 8,
    "rank": 5.5,
    "ts": 2.63,
    "ks": 7.06
  },
  {
    "members": [
      "tsubame",
      "yan",
      "zahir"
    ],
    "appearances": 8,
    "rank": 3.63,
    "ts": 5,
    "ks": 8.31
  },
  {
    "members": [
      "adela",
      "nicky",
      "sua"
    ],
    "appearances": 8,
    "rank": 4,
    "ts": 4.5,
    "ks": 7.69
  },
  {
    "members": [
      "celine",
      "emma",
      "hart"
    ],
    "appearances": 7,
    "rank": 5.14,
    "ts": 2.86,
    "ks": 6.14
  },
  {
    "members": [
      "aiden",
      "eleven",
      "rozzi"
    ],
    "appearances": 7,
    "rank": 4,
    "ts": 4.57,
    "ks": 7.64
  },
  {
    "members": [
      "hart",
      "justina",
      "katja"
    ],
    "appearances": 7,
    "rank": 5.29,
    "ts": 3.29,
    "ks": 6.21
  },
  {
    "members": [
      "leni",
      "mai",
      "shoichi"
    ],
    "appearances": 6,
    "rank": 3.33,
    "ts": 6.17,
    "ks": 9.92
  },
  {
    "members": [
      "coreline",
      "hart",
      "haze"
    ],
    "appearances": 6,
    "rank": 5.5,
    "ts": 2.67,
    "ks": 7.5
  },
  {
    "members": [
      "bianca",
      "fiora",
      "william"
    ],
    "appearances": 6,
    "rank": 2.5,
    "ts": 6.33,
    "ks": 12.33
  },
  {
    "members": [
      "abigail",
      "arda",
      "istvan"
    ],
    "appearances": 6,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 10.5
  },
  {
    "members": [
      "debi_marlene",
      "johann",
      "tazia"
    ],
    "appearances": 5,
    "rank": 4.4,
    "ts": 3.6,
    "ks": 7.1
  },
  {
    "members": [
      "irem",
      "markus",
      "martina"
    ],
    "appearances": 4,
    "rank": 6.75,
    "ts": 1.25,
    "ks": 3.88
  },
  {
    "members": [
      "johann",
      "markus",
      "theodore"
    ],
    "appearances": 4,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 5.88
  },
  {
    "members": [
      "hart",
      "karla",
      "sissela"
    ],
    "appearances": 4,
    "rank": 5,
    "ts": 3,
    "ks": 7.13
  },
  {
    "members": [
      "nia",
      "rozzi",
      "yan"
    ],
    "appearances": 4,
    "rank": 3.75,
    "ts": 5.25,
    "ks": 6
  },
  {
    "members": [
      "tazia",
      "tsubame",
      "yan"
    ],
    "appearances": 4,
    "rank": 5.25,
    "ts": 3,
    "ks": 4.25
  },
  {
    "members": [
      "karla",
      "katja",
      "tia"
    ],
    "appearances": 4,
    "rank": 5.25,
    "ts": 2.75,
    "ks": 9.5
  },
  {
    "members": [
      "johann",
      "nadine",
      "nicky"
    ],
    "appearances": 4,
    "rank": 6,
    "ts": 2.25,
    "ks": 4.5
  },
  {
    "members": [
      "coreline",
      "emma",
      "hart"
    ],
    "appearances": 4,
    "rank": 1.25,
    "ts": 9.25,
    "ks": 9.13
  },
  {
    "members": [
      "bianca",
      "nicky",
      "tsubame"
    ],
    "appearances": 4,
    "rank": 5.75,
    "ts": 2.25,
    "ks": 6.75
  },
  {
    "members": [
      "adina",
      "felix",
      "mai"
    ],
    "appearances": 4,
    "rank": 4.25,
    "ts": 4.5,
    "ks": 7
  },
  {
    "members": [
      "bianca",
      "fiora",
      "rozzi"
    ],
    "appearances": 4,
    "rank": 5.5,
    "ts": 3.25,
    "ks": 8.5
  },
  {
    "members": [
      "fiora",
      "mai",
      "rozzi"
    ],
    "appearances": 4,
    "rank": 2.25,
    "ts": 6.75,
    "ks": 10.25
  },
  {
    "members": [
      "bernice",
      "katja",
      "sissela"
    ],
    "appearances": 4,
    "rank": 4.75,
    "ts": 4,
    "ks": 7
  },
  {
    "members": [
      "hyejin",
      "karla",
      "yan"
    ],
    "appearances": 4,
    "rank": 5,
    "ts": 3,
    "ks": 5.75
  },
  {
    "members": [
      "jackie",
      "li_dailin",
      "martina"
    ],
    "appearances": 4,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 7.5
  },
  {
    "members": [
      "hart",
      "haze",
      "justina"
    ],
    "appearances": 4,
    "rank": 4.5,
    "ts": 3.75,
    "ks": 7.88
  },
  {
    "members": [
      "irem",
      "nia",
      "yan"
    ],
    "appearances": 4,
    "rank": 5,
    "ts": 3.75,
    "ks": 8
  },
  {
    "members": [
      "coreline",
      "karla",
      "rozzi"
    ],
    "appearances": 4,
    "rank": 5,
    "ts": 3.75,
    "ks": 4.38
  },
  {
    "members": [
      "markus",
      "priya",
      "theodore"
    ],
    "appearances": 4,
    "rank": 4.25,
    "ts": 4,
    "ks": 6.38
  },
  {
    "members": [
      "irem",
      "mai",
      "william"
    ],
    "appearances": 4,
    "rank": 4.75,
    "ts": 4,
    "ks": 5.38
  },
  {
    "members": [
      "emma",
      "irem",
      "sua"
    ],
    "appearances": 4,
    "rank": 4,
    "ts": 4,
    "ks": 8.38
  },
  {
    "members": [
      "alonso",
      "nia",
      "rozzi"
    ],
    "appearances": 4,
    "rank": 5.25,
    "ts": 3.5,
    "ks": 6.63
  },
  {
    "members": [
      "coreline",
      "hart",
      "karla"
    ],
    "appearances": 4,
    "rank": 2.75,
    "ts": 6.75,
    "ks": 10.63
  },
  {
    "members": [
      "coreline",
      "emma",
      "garnet"
    ],
    "appearances": 4,
    "rank": 5,
    "ts": 3,
    "ks": 6.75
  },
  {
    "members": [
      "alonso",
      "nadine",
      "sissela"
    ],
    "appearances": 4,
    "rank": 4.75,
    "ts": 3.5,
    "ks": 5.75
  },
  {
    "members": [
      "emma",
      "katja",
      "sissela"
    ],
    "appearances": 4,
    "rank": 3,
    "ts": 6,
    "ks": 8.25
  },
  {
    "members": [
      "coreline",
      "nadine",
      "priya"
    ],
    "appearances": 4,
    "rank": 1.75,
    "ts": 8.5,
    "ks": 9.5
  },
  {
    "members": [
      "mai",
      "nadine",
      "theodore"
    ],
    "appearances": 4,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 5
  },
  {
    "members": [
      "arda",
      "bihyung",
      "kenneth"
    ],
    "appearances": 4,
    "rank": 3.5,
    "ts": 5.25,
    "ks": 11.25
  },
  {
    "members": [
      "adela",
      "coreline",
      "hart"
    ],
    "appearances": 3,
    "rank": 5,
    "ts": 3,
    "ks": 4.33
  },
  {
    "members": [
      "kenneth",
      "priya",
      "silvia"
    ],
    "appearances": 3,
    "rank": 6.33,
    "ts": 1.67,
    "ks": 4.5
  },
  {
    "members": [
      "alonso",
      "arda",
      "tazia"
    ],
    "appearances": 3,
    "rank": 5.33,
    "ts": 3,
    "ks": 4.67
  },
  {
    "members": [
      "nia",
      "piolo",
      "silvia"
    ],
    "appearances": 3,
    "rank": 6,
    "ts": 2,
    "ks": 7
  },
  {
    "members": [
      "arda",
      "piolo",
      "yan"
    ],
    "appearances": 3,
    "rank": 6.33,
    "ts": 1.67,
    "ks": 4.5
  },
  {
    "members": [
      "hart",
      "haze",
      "zahir"
    ],
    "appearances": 3,
    "rank": 4.67,
    "ts": 4.33,
    "ks": 5.17
  },
  {
    "members": [
      "chloe",
      "mirka",
      "silvia"
    ],
    "appearances": 3,
    "rank": 2.33,
    "ts": 6.33,
    "ks": 8.83
  },
  {
    "members": [
      "alonso",
      "bernice",
      "theodore"
    ],
    "appearances": 3,
    "rank": 3.33,
    "ts": 6,
    "ks": 8.33
  },
  {
    "members": [
      "johann",
      "justina",
      "katja"
    ],
    "appearances": 3,
    "rank": 4.33,
    "ts": 4,
    "ks": 9.33
  },
  {
    "members": [
      "felix",
      "leni",
      "tazia"
    ],
    "appearances": 3,
    "rank": 6,
    "ts": 2,
    "ks": 3
  },
  {
    "members": [
      "charlotte",
      "hart",
      "tazia"
    ],
    "appearances": 3,
    "rank": 2,
    "ts": 7,
    "ks": 8.83
  },
  {
    "members": [
      "hyunwoo",
      "leni",
      "markus"
    ],
    "appearances": 3,
    "rank": 3.67,
    "ts": 5.33,
    "ks": 5.67
  },
  {
    "members": [
      "abigail",
      "arda",
      "piolo"
    ],
    "appearances": 3,
    "rank": 3.33,
    "ts": 5,
    "ks": 4.5
  },
  {
    "members": [
      "leni",
      "luke",
      "markus"
    ],
    "appearances": 3,
    "rank": 4.67,
    "ts": 4.33,
    "ks": 6
  },
  {
    "members": [
      "aiden",
      "markus",
      "priya"
    ],
    "appearances": 3,
    "rank": 1.33,
    "ts": 9,
    "ks": 13.33
  },
  {
    "members": [
      "charlotte",
      "nicky",
      "tazia"
    ],
    "appearances": 3,
    "rank": 5.33,
    "ts": 2.67,
    "ks": 6
  },
  {
    "members": [
      "camilo",
      "johann",
      "tia"
    ],
    "appearances": 2,
    "rank": 7,
    "ts": 1,
    "ks": 3.5
  },
  {
    "members": [
      "camilo",
      "cathy",
      "tia"
    ],
    "appearances": 2,
    "rank": 7.5,
    "ts": 0.5,
    "ks": 8.25
  },
  {
    "members": [
      "arda",
      "mirka",
      "rozzi"
    ],
    "appearances": 2,
    "rank": 6,
    "ts": 2,
    "ks": 5.5
  },
  {
    "members": [
      "kenneth",
      "nicky",
      "theodore"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3.5,
    "ks": 6.75
  },
  {
    "members": [
      "bianca",
      "fiora",
      "sua"
    ],
    "appearances": 2,
    "rank": 4.5,
    "ts": 3.5,
    "ks": 4.25
  },
  {
    "members": [
      "aiden",
      "nia",
      "nicky"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 4.5,
    "ks": 10.75
  },
  {
    "members": [
      "abigail",
      "arda",
      "nicky"
    ],
    "appearances": 2,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 5.25
  },
  {
    "members": [
      "mai",
      "william",
      "yan"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3,
    "ks": 9
  },
  {
    "members": [
      "arda",
      "blair",
      "piolo"
    ],
    "appearances": 2,
    "rank": 4.5,
    "ts": 4,
    "ks": 11
  },
  {
    "members": [
      "charlotte",
      "karla",
      "rio"
    ],
    "appearances": 2,
    "rank": 1,
    "ts": 10,
    "ks": 12.25
  },
  {
    "members": [
      "debi_marlene",
      "johann",
      "yumin"
    ],
    "appearances": 2,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 5.25
  },
  {
    "members": [
      "arda",
      "echion",
      "jenny"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 4.5,
    "ks": 7.75
  },
  {
    "members": [
      "arda",
      "estelle",
      "piolo"
    ],
    "appearances": 2,
    "rank": 6,
    "ts": 2,
    "ks": 6
  },
  {
    "members": [
      "johann",
      "nicky",
      "yumin"
    ],
    "appearances": 2,
    "rank": 6.5,
    "ts": 1.5,
    "ks": 4
  },
  {
    "members": [
      "arda",
      "justina",
      "rio"
    ],
    "appearances": 2,
    "rank": 7,
    "ts": 1,
    "ks": 2.25
  },
  {
    "members": [
      "abigail",
      "hyejin",
      "piolo"
    ],
    "appearances": 2,
    "rank": 6,
    "ts": 2,
    "ks": 5.5
  },
  {
    "members": [
      "adela",
      "lenox",
      "nadine"
    ],
    "appearances": 2,
    "rank": 4,
    "ts": 5.5,
    "ks": 8.75
  },
  {
    "members": [
      "chloe",
      "eva",
      "johann"
    ],
    "appearances": 2,
    "rank": 4,
    "ts": 4,
    "ks": 4
  },
  {
    "members": [
      "nicky",
      "tazia",
      "william"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 5,
    "ks": 8
  },
  {
    "members": [
      "echion",
      "jenny",
      "johann"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 4.5,
    "ks": 7.5
  },
  {
    "members": [
      "eva",
      "hart",
      "sissela"
    ],
    "appearances": 2,
    "rank": 6.5,
    "ts": 1.5,
    "ks": 3.75
  },
  {
    "members": [
      "coreline",
      "haze",
      "karla"
    ],
    "appearances": 2,
    "rank": 2.5,
    "ts": 6,
    "ks": 9.5
  },
  {
    "members": [
      "coreline",
      "hart",
      "nadine"
    ],
    "appearances": 2,
    "rank": 4,
    "ts": 4,
    "ks": 5.5
  },
  {
    "members": [
      "coreline",
      "haze",
      "sissela"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3,
    "ks": 8
  },
  {
    "members": [
      "arda",
      "chiara",
      "fiora"
    ],
    "appearances": 2,
    "rank": 7.5,
    "ts": 0.5,
    "ks": 3.25
  },
  {
    "members": [
      "chiara",
      "johann",
      "nadine"
    ],
    "appearances": 2,
    "rank": 7,
    "ts": 1,
    "ks": 2.75
  },
  {
    "members": [
      "debi_marlene",
      "hart",
      "tazia"
    ],
    "appearances": 2,
    "rank": 4,
    "ts": 4,
    "ks": 10.5
  },
  {
    "members": [
      "garnet",
      "johann",
      "yumin"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 5,
    "ks": 8
  },
  {
    "members": [
      "jenny",
      "justina",
      "mai"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3,
    "ks": 8.75
  },
  {
    "members": [
      "li_dailin",
      "nia",
      "william"
    ],
    "appearances": 2,
    "rank": 6,
    "ts": 2,
    "ks": 3.75
  },
  {
    "members": [
      "darko",
      "debi_marlene",
      "hyejin"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3.5,
    "ks": 8
  },
  {
    "members": [
      "adriana",
      "luke",
      "piolo"
    ],
    "appearances": 2,
    "rank": 4.5,
    "ts": 3.5,
    "ks": 9.25
  },
  {
    "members": [
      "hisui",
      "johann",
      "mai"
    ],
    "appearances": 2,
    "rank": 3,
    "ts": 5,
    "ks": 9.25
  },
  {
    "members": [
      "fiora",
      "leni",
      "markus"
    ],
    "appearances": 2,
    "rank": 5,
    "ts": 3,
    "ks": 7.25
  },
  {
    "members": [
      "bianca",
      "fiora",
      "tsubame"
    ],
    "appearances": 2,
    "rank": 6.5,
    "ts": 1.5,
    "ks": 7.75
  },
  {
    "members": [
      "arda",
      "blair",
      "kenneth"
    ],
    "appearances": 2,
    "rank": 5.5,
    "ts": 2.5,
    "ks": 4.5
  },
  {
    "members": [
      "bernice",
      "coreline",
      "haze"
    ],
    "appearances": 2,
    "rank": 6.5,
    "ts": 1.5,
    "ks": 3.75
  },
  {
    "members": [
      "hart",
      "haze",
      "katja"
    ],
    "appearances": 2,
    "rank": 2.5,
    "ts": 6,
    "ks": 6.75
  },
  {
    "members": [
      "abigail",
      "johann",
      "mai"
    ],
    "appearances": 2,
    "rank": 6.5,
    "ts": 1.5,
    "ks": 8
  },
  {
    "members": [
      "henry",
      "nadine",
      "sissela"
    ],
    "appearances": 2,
    "rank": 4.5,
    "ts": 4,
    "ks": 4.75
  },
  {
    "members": [
      "bihyung",
      "leni",
      "markus"
    ],
    "appearances": 2,
    "rank": 6,
    "ts": 2,
    "ks": 6.75
  },
  {
    "members": [
      "alonso",
      "henry",
      "theodore"
    ],
    "appearances": 2,
    "rank": 4.5,
    "ts": 3.5,
    "ks": 5.25
  },
  {
    "members": [
      "charlotte",
      "echion",
      "jenny"
    ],
    "appearances": 2,
    "rank": 2,
    "ts": 7.5,
    "ks": 8.75
  },
  {
    "members": [
      "alonso",
      "tazia",
      "william"
    ],
    "appearances": 2,
    "rank": 7,
    "ts": 1,
    "ks": 5.25
  },
  {
    "members": [
      "chloe",
      "eva",
      "garnet"
    ],
    "appearances": 2,
    "rank": 7.5,
    "ts": 0.5,
    "ks": 3.75
  },
  {
    "members": [
      "mai",
      "piolo",
      "theodore"
    ],
    "appearances": 2,
    "rank": 3.5,
    "ts": 5,
    "ks": 9.25
  },
  {
    "members": [
      "hart",
      "irem",
      "sissela"
    ],
    "appearances": 2,
    "rank": 4,
    "ts": 5.5,
    "ks": 12.25
  }
];
