export const TOURNAMENT_META_SOURCE = {
  label: "recent_tournament_manual",
  note: "Recent tournament compositions entered from shared match screenshots. Scores are composition-focused, not single-character strength.",
};

export const tournamentCompositions = [
  { team: "ROX", rank: 1, ts: 24, ks: 14, members: ["markus", "leni", "luke"] },
  { team: "JNE", rank: 2, ts: 14.5, ks: 7.5, members: ["mai", "tsubame", "nia"] },
  { team: "GIN", rank: 3, ts: 15.5, ks: 10.5, members: ["karla", "haze", "coreline"] },
  { team: "YJS", rank: 4, ts: 11.5, ks: 7.5, members: ["alonso", "theodore", "nia"] },
  { team: "GBS", rank: 5, ts: 5, ks: 2, members: ["hart", "coreline", "nadine"] },
  { team: "FN", rank: 6, ts: 8, ks: 6, members: ["sissela", "haze", "coreline"] },
  { team: "MIR", rank: 7, ts: 9, ks: 8, members: ["silvia", "justina", "echion"] },
  { team: "GSL", rank: 8, ts: 2.5, ks: 2.5, members: ["sua", "johann", "katja"] },

  { team: "YJS", rank: 1, ts: 20, ks: 10, members: ["vanya", "katja", "sissela"] },
  { team: "GIN", rank: 2, ts: 15.5, ks: 8.5, members: ["karla", "haze", "coreline"] },
  { team: "GBS", rank: 3, ts: 14, ks: 9, members: ["hart", "coreline", "nadine"] },
  { team: "FN", rank: 4, ts: 14, ks: 10, members: ["sissela", "haze", "coreline"] },
  { team: "GSL", rank: 5, ts: 5, ks: 2, members: ["nia", "alonso", "tsubame"] },
  { team: "ROX", rank: 6, ts: 11, ks: 9, members: ["jackie", "theodore", "yuki"] },
  { team: "MIR", rank: 7, ts: 1.5, ks: 0.5, members: ["nadine", "coreline", "haze"] },
  { team: "JNE", rank: 8, ts: 0.5, ks: 0.5, members: ["katja", "hart", "sissela"] },

  { team: "JNE", rank: 1, ts: 34, ks: 24, members: ["alonso", "tsubame", "nia"] },
  { team: "GBS", rank: 2, ts: 15, ks: 8, members: ["rio", "alonso", "justina"] },
  { team: "FN", rank: 3, ts: 9.5, ks: 4.5, members: ["markus", "leni", "hyunwoo"] },
  { team: "ROX", rank: 4, ts: 9, ks: 5, members: ["echion", "johann", "jenny"] },
  { team: "MIR", rank: 5, ts: 8, ks: 5, members: ["william", "tazia", "nicky"] },
  { team: "GSL", rank: 6, ts: 2.5, ks: 0.5, members: ["leni", "tazia", "felix"] },
  { team: "GIN", rank: 7, ts: 4.5, ks: 3.5, members: ["sissela", "eva", "hart"] },
  { team: "YJS", rank: 8, ts: 1, ks: 1, members: ["vanya", "katja", "sissela"] },

  { team: "FN", rank: 1, ts: 22, ks: 12, members: ["markus", "leni", "hyunwoo"] },
  { team: "MIR", rank: 2, ts: 18, ks: 11, members: ["william", "tazia", "nicky"] },
  { team: "ROX", rank: 3, ts: 15, ks: 10, members: ["echion", "johann", "jenny"] },
  { team: "YJS", rank: 4, ts: 8.5, ks: 4.5, members: ["johann", "chloe", "eva"] },
  { team: "GSL", rank: 5, ts: 7, ks: 4, members: ["karla", "celine", "hart"] },
  { team: "GIN", rank: 6, ts: 6, ks: 4, members: ["sissela", "eva", "hart"] },
  { team: "JNE", rank: 7, ts: 3.5, ks: 2.5, members: ["alonso", "nadine", "adela"] },
  { team: "GBS", rank: 8, ts: 3, ks: 3, members: ["katja", "alonso", "justina"] },

  { team: "JNE", rank: 1, ts: 22, ks: 12, members: ["lenox", "nadine", "adela"] },
  { team: "GSL", rank: 2, ts: 12, ks: 5, members: ["arda", "piolo", "abigail"] },
  { team: "GBS", rank: 3, ts: 11.5, ks: 6.5, members: ["rozzi", "mai", "fiora"] },
  { team: "YJS", rank: 4, ts: 7.5, ks: 3.5, members: ["johann", "chloe", "eva"] },
  { team: "MIR", rank: 5, ts: 4.5, ks: 1.5, members: ["arda", "abigail", "piolo"] },
  { team: "GIN", rank: 6, ts: 15.5, ks: 13.5, members: ["abigail", "istvan", "arda"] },
  { team: "FN", rank: 7, ts: 5, ks: 4, members: ["abigail", "piolo", "hyejin"] },
  { team: "ROX", rank: 8, ts: 3, ks: 3, members: ["arda", "piolo", "istvan"] },

  { team: "GBS", rank: 1, ts: 25, ks: 15, members: ["rozzi", "mai", "fiora"] },
  { team: "ROX", rank: 2, ts: 19, ks: 12, members: ["cathy", "theodore", "yuki"] },
  { team: "MIR", rank: 3, ts: 12, ks: 7, members: ["arda", "abigail", "piolo"] },
  { team: "GIN", rank: 4, ts: 9.5, ks: 5.5, members: ["abigail", "istvan", "arda"] },
  { team: "FN", rank: 5, ts: 10, ks: 7, members: ["abigail", "piolo", "hyejin"] },
  { team: "JNE", rank: 6, ts: 10, ks: 8, members: ["lenox", "rio", "celine"] },
  { team: "GSL", rank: 7, ts: 5, ks: 4, members: ["arda", "garnet", "abigail"] },
  { team: "YJS", rank: 8, ts: 0.5, ks: 0.5, members: ["arda", "rio", "justina"] },

  { team: "GSL", rank: 1, ts: 34.5, ks: 24.5, members: ["bianca", "fiora", "william"] },
  { team: "ROX", rank: 2, ts: 23.5, ks: 16.5, members: ["arda", "piolo", "istvan"] },
  { team: "MIR", rank: 3, ts: 12.5, ks: 7.5, members: ["adina", "felix", "mai"] },
  { team: "FN", rank: 4, ts: 10, ks: 6, members: ["arda", "echion", "jenny"] },
  { team: "GIN", rank: 5, ts: 7.5, ks: 4.5, members: ["yumin", "nicky", "johann"] },
  { team: "YJS", rank: 6, ts: 6, ks: 4, members: ["arda", "rio", "justina"] },
  { team: "JNE", rank: 7, ts: 10, ks: 9, members: ["bianca", "fiora", "rozzi"] },
  { team: "GBS", rank: 8, ts: 1, ks: 1, members: ["arda", "estelle", "piolo"] },

  { team: "MIR", rank: 1, ts: 23.5, ks: 13.5, members: ["adina", "felix", "mai"] },
  { team: "GSL", rank: 2, ts: 19.5, ks: 12.5, members: ["bianca", "fiora", "william"] },
  { team: "FN", rank: 3, ts: 14.5, ks: 9.5, members: ["arda", "echion", "jenny"] },
  { team: "GBS", rank: 4, ts: 15, ks: 11, members: ["arda", "estelle", "piolo"] },
  { team: "YJS", rank: 5, ts: 6, ks: 3, members: ["piolo", "magnus", "nia"] },
  { team: "JNE", rank: 6, ts: 8, ks: 6, members: ["bianca", "fiora", "rozzi"] },
  { team: "ROX", rank: 7, ts: 1.5, ks: 0.5, members: ["hyunwoo", "leni", "markus"] },
  { team: "GIN", rank: 8, ts: 3.5, ks: 3.5, members: ["yumin", "nicky", "johann"] },

  { team: "DTS", rank: 1, ts: 19.5, ks: 9.5, members: ["karla", "charlotte", "rio"] },
  { team: "INW", rank: 2, ts: 20, ks: 13, members: ["tazia", "charlotte", "hart"] },
  { team: "NRG", rank: 3, ts: 11, ks: 6, members: ["arda", "piolo", "istvan"] },
  { team: "JSD", rank: 4, ts: 10, ks: 6, members: ["coreline", "hart", "lenore"] },
  { team: "GBA", rank: 5, ts: 10.5, ks: 7.5, members: ["johann", "debi_marlene", "yumin"] },
  { team: "GNS", rank: 6, ts: 10.5, ks: 8.5, members: ["markus", "justina", "katja"] },
  { team: "DG", rank: 7, ts: 9.5, ks: 8.5, members: ["haze", "hart", "coreline"] },
  { team: "CNJ", rank: 8, ts: 1.5, ks: 1.5, members: ["istvan", "piolo", "arda"] },

  { team: "DTS", rank: 1, ts: 25, ks: 15, members: ["karla", "charlotte", "rio"] },
  { team: "INW", rank: 2, ts: 17, ks: 10, members: ["sissela", "vanya", "priya"] },
  { team: "CNJ", rank: 3, ts: 20.5, ks: 15.5, members: ["istvan", "piolo", "arda"] },
  { team: "NRG", rank: 4, ts: 11.5, ks: 7.5, members: ["arda", "piolo", "istvan"] },
  { team: "JSD", rank: 5, ts: 8, ks: 5, members: ["garnet", "rio", "johann"] },
  { team: "GBA", rank: 6, ts: 5, ks: 3, members: ["johann", "debi_marlene", "yumin"] },
  { team: "GNS", rank: 7, ts: 4.5, ks: 3.5, members: ["markus", "justina", "rio"] },
  { team: "DG", rank: 8, ts: 6.5, ks: 6.5, members: ["haze", "hart", "coreline"] },

  { team: "RECENT-A", rank: 1, ts: 0, ks: 0, members: ["alonso", "nia", "rozzi"] },
  { team: "RECENT-A", rank: 2, ts: 0, ks: 0, members: ["chloe", "mirka", "silvia"] },
  { team: "RECENT-A", rank: 3, ts: 0, ks: 0, members: ["jenny", "johann", "justina"] },
  { team: "RECENT-A", rank: 4, ts: 0, ks: 0, members: ["adriana", "luke", "piolo"] },
  { team: "RECENT-A", rank: 5, ts: 0, ks: 0, members: ["eva", "chloe", "karla"] },
  { team: "RECENT-A", rank: 6, ts: 0, ks: 0, members: ["leni", "yumin", "garnet"] },
  { team: "RECENT-A", rank: 7, ts: 0, ks: 0, members: ["sua", "emma", "irem"] },
  { team: "RECENT-A", rank: 8, ts: 0, ks: 0, members: ["hyejin", "debi_marlene", "darko"] },

  { team: "RECENT-B", rank: 1, ts: 0, ks: 0, members: ["leni", "yumin", "garnet"] },
  { team: "RECENT-B", rank: 2, ts: 0, ks: 0, members: ["chloe", "mirka", "silvia"] },
  { team: "RECENT-B", rank: 3, ts: 0, ks: 0, members: ["sua", "emma", "irem"] },
  { team: "RECENT-B", rank: 4, ts: 0, ks: 0, members: ["jenny", "johann", "justina"] },
  { team: "RECENT-B", rank: 5, ts: 0, ks: 0, members: ["adriana", "luke", "piolo"] },
  { team: "RECENT-B", rank: 6, ts: 0, ks: 0, members: ["eva", "chloe", "karla"] },
  { team: "RECENT-B", rank: 7, ts: 0, ks: 0, members: ["shirin", "debi_marlene", "johann"] },
  { team: "RECENT-B", rank: 8, ts: 0, ks: 0, members: ["alonso", "nia", "rozzi"] },

  { team: "RECENT-C", rank: 1, ts: 0, ks: 0, members: ["silvia", "luke", "piolo"] },
  { team: "RECENT-C", rank: 2, ts: 0, ks: 0, members: ["hyejin", "debi_marlene", "darko"] },
  { team: "RECENT-C", rank: 3, ts: 0, ks: 0, members: ["sua", "emma", "irem"] },
  { team: "RECENT-C", rank: 4, ts: 0, ks: 0, members: ["eva", "chloe", "karla"] },
  { team: "RECENT-C", rank: 5, ts: 0, ks: 0, members: ["alonso", "nia", "rozzi"] },
  { team: "RECENT-C", rank: 6, ts: 0, ks: 0, members: ["leni", "yumin", "garnet"] },
  { team: "RECENT-C", rank: 7, ts: 0, ks: 0, members: ["fiora", "markus", "silvia"] },
  { team: "RECENT-C", rank: 8, ts: 0, ks: 0, members: ["jenny", "johann", "justina"] },

  { team: "RECENT-D", rank: 1, ts: 0, ks: 0, members: ["jenny", "johann", "justina"] },
  { team: "RECENT-D", rank: 2, ts: 0, ks: 0, members: ["fiora", "markus", "silvia"] },
  { team: "RECENT-D", rank: 3, ts: 0, ks: 0, members: ["sua", "emma", "irem"] },
  { team: "RECENT-D", rank: 4, ts: 0, ks: 0, members: ["eva", "chloe", "karla"] },
  { team: "RECENT-D", rank: 5, ts: 0, ks: 0, members: ["silvia", "luke", "piolo"] },
  { team: "RECENT-D", rank: 6, ts: 0, ks: 0, members: ["leni", "yumin", "garnet"] },
  { team: "RECENT-D", rank: 7, ts: 0, ks: 0, members: ["alonso", "nia", "rozzi"] },
  { team: "RECENT-D", rank: 8, ts: 0, ks: 0, members: ["luke", "debi_marlene", "johann"] },

  { team: "RECENT-E", rank: 1, ts: 0, ks: 0, members: ["katja", "justina", "hart"] },
  { team: "RECENT-E", rank: 2, ts: 0, ks: 0, members: ["nia", "tsubame", "alonso"] },
  { team: "RECENT-E", rank: 3, ts: 0, ks: 0, members: ["chiara", "jenny", "johann"] },
  { team: "RECENT-E", rank: 4, ts: 0, ks: 0, members: ["zahir", "yan", "tsubame"] },
  { team: "RECENT-E", rank: 5, ts: 0, ks: 0, members: ["silvia", "emma", "piolo"] },
  { team: "RECENT-E", rank: 6, ts: 0, ks: 0, members: ["johann", "vanya", "garnet"] },
  { team: "RECENT-E", rank: 7, ts: 0, ks: 0, members: ["fiora", "chiara", "arda"] },
  { team: "RECENT-E", rank: 8, ts: 0, ks: 0, members: ["chiara", "nadine", "johann"] },

  { team: "RECENT-F", rank: 1, ts: 0, ks: 0, members: ["istvan", "piolo", "arda"] },
  { team: "RECENT-F", rank: 2, ts: 0, ks: 0, members: ["silvia", "emma", "piolo"] },
  { team: "RECENT-F", rank: 3, ts: 0, ks: 0, members: ["nia", "tsubame", "alonso"] },
  { team: "RECENT-F", rank: 4, ts: 0, ks: 0, members: ["fiora", "camilo", "arda"] },
  { team: "RECENT-F", rank: 5, ts: 0, ks: 0, members: ["priya", "vanya", "garnet"] },
  { team: "RECENT-F", rank: 6, ts: 0, ks: 0, members: ["zahir", "yan", "tsubame"] },
  { team: "RECENT-F", rank: 7, ts: 0, ks: 0, members: ["katja", "justina", "hart"] },
  { team: "RECENT-F", rank: 8, ts: 0, ks: 0, members: ["barbara", "sissela", "priya"] },

  { team: "RECENT-G", rank: 1, ts: 0, ks: 0, members: ["priya", "aiden", "markus"] },
  { team: "RECENT-G", rank: 2, ts: 0, ks: 0, members: ["rozzi", "nia", "li_dailin"] },
  { team: "RECENT-G", rank: 3, ts: 0, ks: 0, members: ["hyejin", "yan", "karla"] },
  { team: "RECENT-G", rank: 4, ts: 0, ks: 0, members: ["li_dailin", "jackie", "martina"] },
  { team: "RECENT-G", rank: 5, ts: 0, ks: 0, members: ["abigail", "emma", "daniel"] },
  { team: "RECENT-G", rank: 6, ts: 0, ks: 0, members: ["camilo", "magnus", "silvia"] },
  { team: "RECENT-G", rank: 7, ts: 0, ks: 0, members: ["haze", "justina", "hart"] },
  { team: "RECENT-G", rank: 8, ts: 0, ks: 0, members: ["nia", "irem", "yan"] },

  { team: "RECENT-H", rank: 1, ts: 0, ks: 0, members: ["nia", "irem", "yan"] },
  { team: "RECENT-H", rank: 2, ts: 0, ks: 0, members: ["priya", "aiden", "markus"] },
  { team: "RECENT-H", rank: 3, ts: 0, ks: 0, members: ["li_dailin", "jackie", "martina"] },
  { team: "RECENT-H", rank: 4, ts: 0, ks: 0, members: ["haze", "justina", "hart"] },
  { team: "RECENT-H", rank: 5, ts: 0, ks: 0, members: ["camilo", "magnus", "silvia"] },
  { team: "RECENT-H", rank: 6, ts: 0, ks: 0, members: ["hyejin", "yan", "karla"] },
  { team: "RECENT-H", rank: 7, ts: 0, ks: 0, members: ["rozzi", "nia", "li_dailin"] },
  { team: "RECENT-H", rank: 8, ts: 0, ks: 0, members: ["abigail", "emma", "daniel"] },
];

export function tournamentPairKey(a, b) {
  return [a, b].sort().join(":");
}

export function tournamentComboKey(members) {
  return [...members].sort().join(":");
}
