export const weaponTemplates = {
  glove: ["assets/weapons/glove.png"],
  tonfa: ["assets/weapons/tonfa.png"],
  bat: ["assets/weapons/bat.png"],
  hammer: ["assets/weapons/hammer.png"],
  whip: ["assets/weapons/whip.png"],
  throw: ["assets/weapons/throw.png"],
  shuriken: ["assets/weapons/shuriken.png"],
  bow: ["assets/weapons/bow.png"],
  crossbow: ["assets/weapons/crossbow.png"],
  pistol: ["assets/weapons/pistol.png"],
  assault_rifle: ["assets/weapons/assault_rifle.png"],
  sniper_rifle: ["assets/weapons/sniper_rifle.png"],
  axe: ["assets/weapons/axe.png"],
  dagger: ["assets/weapons/dagger.png"],
  two_handed_sword: ["assets/weapons/two_handed_sword.png"],
  dual_swords: ["assets/weapons/dual_swords.png"],
  spear: ["assets/weapons/spear.png"],
  nunchaku: ["assets/weapons/nunchaku.png"],
  rapier: ["assets/weapons/rapier.png"],
  guitar: ["assets/weapons/guitar.png"],
  camera: ["assets/weapons/camera.png"],
  arcana: ["assets/weapons/arcana.png"],
  vf_prosthetic: ["assets/weapons/vf_prosthetic.png"],
};
